import test from 'node:test';
import assert from 'node:assert/strict';
import {syntheticRentOpsSnapshot} from '../fixtures/synthetic';
import {tenantAccountLedgerRows,presentTenantHome,eligibleTenantTenancies} from './presentation';
import {payableAccount,eligibleCharges} from '../payments/model';
test('exact RM account history extends current grant without widening native or other accounts',()=>{
 const s=structuredClone(syntheticRentOpsSnapshot());const t=s.tenancies[0],p=s.people.find(p=>p.id===t.primaryPersonId)!;p.source={system:'rent_manager',entityType:'person',sourceId:'887'};
 const base=s.ledgerTransactions.find(r=>r.tenancyId===t.id)!;
 const rm={...base,id:'source-account-charge',tenancyId:null,personId:p.id,source:{system:'rent_manager' as const,entityType:'ledger_transaction' as const,sourceId:'charge:1'},sourceArtifactSha256:'a'.repeat(64),personLinkKnowledge:'exact' as const,tenancyLinkKnowledge:'unknown' as const,status:null,statusKnowledge:'unknown' as const};
 s.ledgerTransactions=[rm,{...rm,id:'native',source:undefined},{...rm,id:'other-system',source:{...rm.source,system:'manual'}},{...rm,id:'other-person',personId:'someone-else'},{...rm,id:'unbound',sourceArtifactSha256:null} ] as typeof s.ledgerTransactions;
 const identity={id:'test',personId:p.id,tenancyId:t.id,email:'',status:'active' as const};
 assert.deepEqual(tenantAccountLedgerRows(s,identity).map(r=>r.id),['source-account-charge']);
 const home=presentTenantHome(s,identity,'2026-09-07')!;assert.equal(home.ledger.length,1);assert.equal(home.balance.complete,false);assert.equal(home.balance.amountCents,null);
 assert.equal(payableAccount(s,identity,[],new Date('2026-09-07T12:00:00Z')).reason,'balance_review_required');
 s.ledgerTransactions=[{...rm,status:'posted',statusKnowledge:'source',kind:'charge',amountCents:120000,amountKnowledge:'known',postedOn:'2026-09-01',postedOnKnowledge:'source',category:'base_rent',categoryKnowledge:'source',dueOn:'2026-09-01'}];s.paymentAllocations=[];
 assert.equal(eligibleCharges(s,t.id,'2026-09-07')[0]?.openCents,120000);
 assert.equal(presentTenantHome(s,identity,'2026-09-07')!.balance.amountCents,120000);
 s.subsidyContracts=[];
 const receipt={...s.ledgerTransactions[0],id:'source-payment',kind:'payment' as const,amountCents:20000,category:null,categoryKnowledge:'unknown' as const,source:{...rm.source,sourceId:'payment:2'}};
 s.ledgerTransactions.push(receipt);
 assert.equal(payableAccount(s,identity,[],new Date('2026-09-07T12:00:00Z')).payableCents,100000);
 p.paymentReviewReason='assistance_responsibility_unverified';
 p.paymentReviewArtifactSha256='b'.repeat(64);p.paymentReviewSourceReference='private-source-pointer';
 const publicChoice=eligibleTenantTenancies(s).find(row=>row.personId===p.id)!;
 assert.equal(publicChoice.paymentReviewReason,'assistance_responsibility_unverified');
 assert.equal(JSON.stringify(publicChoice).includes('private-source-pointer'),false);
 assert.equal(JSON.stringify(publicChoice).includes('b'.repeat(64)),false);
 assert.equal(payableAccount(s,identity,[],new Date('2026-09-07T12:00:00Z')).reason,'assistance_responsibility_unverified');
 assert.equal(presentTenantHome(s,identity,'2026-09-07')!.balance.amountCents,100000);
 p.paymentReviewReason=null;
 s.ledgerTransactions[0].propertyId='historical-property';
 assert.equal(payableAccount(s,identity,[],new Date('2026-09-07T12:00:00Z')).reason,'account_scope_payment_review_required');
});

test('paid deposit does not consume rent payable and unpaid deposit is not collected as rent',()=>{
 const s=structuredClone(syntheticRentOpsSnapshot());const t=s.tenancies[0];s.subsidyContracts=[];
 const base=s.ledgerTransactions.find(r=>r.tenancyId===t.id)!;
 const rent={...base,id:'rent',kind:'charge' as const,category:'base_rent' as const,status:'posted' as const,amountCents:120000,postedOn:'2026-09-01',dueOn:'2026-09-01'};
 const deposit={...rent,id:'deposit',category:'security_deposit' as const,amountCents:100000};
 const payment={...rent,id:'deposit-receipt',kind:'payment' as const,category:null,amountCents:100000};
 s.ledgerTransactions=[rent,deposit,payment];s.paymentAllocations=[{id:'deposit-application',paymentTransactionId:payment.id,chargeTransactionId:deposit.id,amountCents:100000,allocatedOn:'2026-09-01'}];
 const identity={personId:t.primaryPersonId,tenancyId:t.id};const now=new Date('2026-09-07T12:00:00Z');
 assert.equal(payableAccount(s,identity,[],now).payableCents,120000);
 assert.deepEqual(eligibleCharges(s,t.id,'2026-09-07').map(r=>r.transaction.id),['rent']);
 s.ledgerTransactions=[deposit];s.paymentAllocations=[];
 assert.equal(payableAccount(s,identity,[],now).payableCents,0);
 s.ledgerTransactions=[rent,deposit];
 assert.equal(payableAccount(s,identity,[],now).payableCents,120000);
});

test('paid native previous lease stays balanced alongside current RM account rent',()=>{
 const s=structuredClone(syntheticRentOpsSnapshot());const t=s.tenancies[0],p=s.people.find(p=>p.id===t.primaryPersonId)!;p.source={system:'rent_manager',entityType:'person',sourceId:'887'};
 const previous={...t,id:'previous',primaryPersonLinkKnowledge:'manual' as const,propertyLinkKnowledge:'manual' as const,unitLinkKnowledge:'manual' as const};s.tenancies.push(previous);s.subsidyContracts=[];s.paymentAllocations=[];
 const base=s.ledgerTransactions.find(r=>r.tenancyId===t.id)!;
 const old={...base,id:'old-rent',tenancyId:previous.id,personId:p.id,kind:'charge' as const,amountCents:10000,status:'posted' as const,postedOn:'2026-08-01',dueOn:'2026-08-01',category:'base_rent' as const,personLinkKnowledge:'manual' as const,tenancyLinkKnowledge:'manual' as const,propertyLinkKnowledge:'manual' as const,unitLinkKnowledge:'manual' as const};
 const paid={...old,id:'old-paid',kind:'payment' as const};
 const current={...old,id:'current-rent',tenancyId:null,postedOn:'2026-09-01',dueOn:'2026-09-01',source:{system:'rent_manager' as const,entityType:'ledger_transaction' as const,sourceId:'charge:3'},sourceArtifactSha256:'a'.repeat(64),personLinkKnowledge:'exact' as const};
 s.ledgerTransactions=[old,paid,current];s.paymentAllocations=[{id:'old-applied',paymentTransactionId:paid.id,chargeTransactionId:old.id,amountCents:10000,allocatedOn:'2026-08-01'}];
 const identity={id:'test',personId:p.id,tenancyId:t.id,email:'',status:'active' as const};
 assert.equal(presentTenantHome(s,identity,'2026-09-07')!.balance.amountCents,10000);
 assert.equal(payableAccount(s,identity,[],new Date('2026-09-07T12:00:00Z')).payableCents,10000);
 old.personLinkKnowledge='unknown' as any;
 assert.equal(tenantAccountLedgerRows(s,identity).some(r=>r.id===old.id),false);
 assert.equal(presentTenantHome(s,identity,'2026-09-07')!.balance.complete,false);
});
test('unknown category closes only with valid allocations effective as of checkout and reopens on reversal',()=>{
 const s=structuredClone(syntheticRentOpsSnapshot());const t=s.tenancies[0];s.subsidyContracts=[];
 const base=s.ledgerTransactions.find(r=>r.tenancyId===t.id)!;
 const rent={...base,id:'rent',kind:'charge' as const,category:'base_rent' as const,status:'posted' as const,amountCents:120000,postedOn:'2026-09-01',dueOn:'2026-09-01'};
 const unknown={...rent,id:'unknown',category:null,categoryKnowledge:'unknown' as const,amountCents:85000};
 const paid={...rent,id:'paid',kind:'payment' as const,amountCents:85000};
 s.ledgerTransactions=[rent,unknown,paid];
 const allocation={id:'applied',paymentTransactionId:paid.id,chargeTransactionId:unknown.id,amountCents:85000,allocatedOn:'2026-09-01'};
 s.paymentAllocations=[allocation];const identity={personId:t.primaryPersonId,tenancyId:t.id};const now=new Date('2026-09-07T12:00:00Z');
 assert.equal(payableAccount(s,identity,[],now).payableCents,120000);
 allocation.amountCents=84000;assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');
 allocation.amountCents=85000;allocation.allocatedOn='2026-09-08';assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');
 allocation.allocatedOn='2026-09-01';paid.status='voided' as any;assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');
 paid.status='posted';s.ledgerTransactions.push({...paid,id:'return',kind:'reversal',reversalOfId:paid.id,postedOn:'2026-09-07'});assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');
});

test('same-property paid former-unit history permits only current-unit charges',()=>{
 const s=structuredClone(syntheticRentOpsSnapshot());const t=s.tenancies[0],p=s.people.find(p=>p.id===t.primaryPersonId)!;p.source={system:'rent_manager',entityType:'person',sourceId:'887'};s.subsidyContracts=[];
 const oldUnit={...s.units.find(u=>u.id===t.unitId)!,id:'old-unit',propertyLinkKnowledge:'manual' as const};s.units.push(oldUnit);
 const base=s.ledgerTransactions.find(r=>r.tenancyId===t.id)!;
 const rent={...base,id:'current',kind:'charge' as const,category:'base_rent' as const,status:'posted' as const,amountCents:120000,postedOn:'2026-09-01',dueOn:'2026-09-01'};
 const old={...rent,id:'old',tenancyId:null,personId:p.id,unitId:oldUnit.id,amountCents:85000,source:{system:'rent_manager' as const,entityType:'ledger_transaction' as const,sourceId:'charge:old'},sourceArtifactSha256:'a'.repeat(64),personLinkKnowledge:'exact' as const,propertyLinkKnowledge:'exact' as const,unitLinkKnowledge:'exact' as const};
 const paid={...rent,id:'paid',kind:'payment' as const,amountCents:85000};s.ledgerTransactions=[rent,old,paid];const allocation={id:'old-application',paymentTransactionId:paid.id,chargeTransactionId:old.id,amountCents:85000,allocatedOn:'2026-09-01'};s.paymentAllocations=[allocation];const identity={personId:p.id,tenancyId:t.id};const now=new Date('2026-09-07T12:00:00Z');
 assert.equal(payableAccount(s,identity,[],now).payableCents,120000);assert.deepEqual(eligibleCharges(s,t.id,'2026-09-07').map(r=>r.transaction.id),['current']);
 s.ledgerTransactions.push({...old,id:'outside-current-reversal',kind:'reversal',personId:'other-person',reversalOfId:rent.id,amountCents:rent.amountCents});assert.equal(payableAccount(s,identity,[],now).payableCents,120000);s.ledgerTransactions.pop();
 s.ledgerTransactions.push({...old,id:'wrong-amount-reversal',kind:'reversal',reversalOfId:old.id,amountCents:1});assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');s.ledgerTransactions.pop();
 s.ledgerTransactions.push({...old,id:'unlinked-reversal',source:undefined,kind:'reversal',reversalOfId:old.id});assert.equal(payableAccount(s,identity,[],now).reason,'balance_review_required');s.ledgerTransactions.pop();
 allocation.amountCents=84000;s.ledgerTransactions.push({...old,id:'foreign-malformed-reversal',kind:'reversal',personId:'other-person',reversalOfId:old.id,amountCents:1});assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');s.ledgerTransactions.pop();allocation.amountCents=85000;
 allocation.allocatedOn='2026-09-08';assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');allocation.allocatedOn='2026-09-01';
 old.propertyId='other-property';assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');old.propertyId=t.propertyId;
 old.unitLinkKnowledge='unknown' as any;assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');old.unitLinkKnowledge='exact';
 paid.status='voided' as any;assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');paid.status='posted';
 s.ledgerTransactions.push({...paid,id:'reversal',kind:'reversal',reversalOfId:paid.id,postedOn:'2026-09-07'});assert.equal(payableAccount(s,identity,[],now).reason,'account_scope_payment_review_required');
});
