import { type Property } from "@shared/schema";
import sunCoveExterior from "@assets/sun-cove-apartments.jpg";
import luciaExterior from "@assets/lucia-apartments.jpg";
import mlkExterior from "@assets/mlk-apartments.jpg";
import sunCoveAfter13 from "@assets/gallery/sun-cove-13-unit-cover-photo.jpg";
import sunCoveAfter13One from "@assets/gallery/sun-cove-13-unit-cover-photo-1.jpg";
import sunCoveAfter13Two from "@assets/gallery/sun-cove-13-unit-cover-photo-2.jpg";
import sunCoveAfter13Three from "@assets/gallery/sun-cove-13-unit-cover-photo-3.jpg";
import sunCoveAfter13Four from "@assets/gallery/sun-cove-13-unit-cover-photo-4.jpg";
import sunCoveAfter21 from "@assets/gallery/sun-cove-21-unit-cover-photo-.jpg";
import sunCoveAfter8 from "@assets/gallery/sun-cove-8-unit-cover-photo-.jpg";
import sunCoveAfter8One from "@assets/gallery/sun-cove-8-unit-cover-photo-1.jpg";
import luciaAfterOne from "@assets/gallery/lucia-1.jpg";
import luciaAfterTwo from "@assets/gallery/lucia-2.jpg";
import luciaAfterThree from "@assets/gallery/lucia-3.jpg";
import luciaAfterFour from "@assets/gallery/lucia-4.jpg";
import luciaAfterFive from "@assets/gallery/lucia-5.jpg";

const d = (value: string) => new Date(value);
const money = (value: number) => value.toFixed(2);

const imgRange = (prefix: string, start: number, end: number, ext = "jpeg") =>
  Array.from({ length: end - start + 1 }, (_, index) => `${prefix}/IMG_${String(start + index).padStart(4, "0")}.${ext}`);

const baseProperty: Property = {
  id: "",
  name: "",
  address: "",
  city: "",
  state: "FL",
  zipCode: "",
  units: 0,
  acquisitionDate: d("2024-01-01T00:00:00.000Z"),
  acquisitionPrice: "0.00",
  rehabCosts: "0.00",
  currentValue: null,
  salePrice: null,
  saleDate: null,
  totalCashflow: "0.00",
  status: "current",
  ownershipStructure: "5Central Capital",
  ownershipName: "5Central Capital",
  yearsHeld: null,
  irr: null,
  equityMultiple: null,
  noi: null,
  debtService: null,
  cashflow: null,
  currentDebt: null,
  refiDate: null,
  projectedSaleDate: null,
  imageUrl: null,
  yearBuilt: null,
  buildingSF: null,
  closingDate: null,
  investmentThesis: null,
  inPlaceNOI: null,
  stabilizedNOI: null,
  noiUpside: null,
  capRateInPlace: null,
  capRateStabilized: null,
  entryCapRate: null,
  exitCapRate: null,
  capRateSpread: null,
  valueCreation: null,
  entryPerUnit: null,
  exitPerUnit: null,
  arvPerUnit: null,
  arvTotal: null,
  bridgeLoan: null,
  ltvPurchase: null,
  ltc: null,
  interestRate: null,
  rehabHoldback: null,
  totalCommitment: null,
  monthlyPI: null,
  annualDebtService: null,
  maturityDate: null,
  loanType: null,
  irrLevered: null,
  moic: null,
  yieldOnCost: null,
  cashYieldStabilized: null,
  paybackPeriod: null,
  holdPeriod: null,
  refiMonth: null,
  sponsorEquity: null,
  breakevenOccupancy: null,
  dscrStabilized: null,
  debtYield: null,
  cashOutAtRefi: null,
  netCashFromSale: null,
  totalProfit: null,
  totalUnits: null,
  occupiedUnits: null,
  occupancyRate: null,
  inPlaceRent: null,
  proformaRent: null,
  rentUpside: null,
  refiLTV: null,
  refiLoanAmount: null,
  refiCashOut: null,
  newMonthlyPI: null,
  equityAfterRefi: null,
  refiTargetMonth: null,
  projectedSalePrice: null,
  projectedNetProceeds: null,
  projectedTotalProfit: null,
  holdPeriodMonths: null,
  beforePhotos: null,
  afterPhotos: null,
  initialCapitalRequired: null,
  totalCashflowCollected: null,
  saleProceeds: null,
  cashOnCash: null,
  totalReturnPercent: null,
  appreciationPercent: null,
  pricePerUnit: null,
  totalBasis: null,
  grossProfit: null,
  roc: null,
  avgAnnualReturn: null,
  profitPerUnit: null,
  phase: null,
  lender: null,
  refiTarget: null,
  monthlyRent: null,
  occupancyStatus: null,
};

const property = (input: Partial<Property> & Pick<Property, "id" | "name" | "address" | "city" | "state" | "zipCode" | "units" | "acquisitionDate" | "acquisitionPrice" | "status" | "ownershipStructure" | "ownershipName">): Property => ({
  ...baseProperty,
  ...input,
});

export interface PublicPropertyMeta {
  slug: string;
  assetClass: "multifamily" | "single_family_flip" | "sold";
  cardImage: string;
  publicStatus: string;
  shortThesis: string;
  sourceNote: string;
  photoCount?: number;
}

export const publicPortfolioFacts = {
  publicAum: 9_271_153.85,
  publicAumLabel: "$9.3M",
  publicAumNote: "Approved property-level values. Ownership discounts are not applied.",
  activeMultifamilyUnits: 55,
  activeMultifamilyAssets: 4,
  activeFlipProjects: 3,
  activeProjectCount: 7,
  currentOccupancy: 39 / 55,
  occupiedUnits: 39,
  vacantUnits: 16,
  inPlaceMonthlyRent: 52_820,
  proformaMonthlyRent: 81_000,
  monthlyRentUpside: 28_180,
  underwrittenNOI: 615_669.54,
  totalBasis: 6_000_000,
  currentMortgageDebt: 5_461_089.64,
  portfolioEquity: 3_810_064.21,
  weightedCapRate: 0.0664070,
  yieldOnCost: 0.1026116,
  projected2026Aum: 23_760_000,
  projected2026Units: 124,
};

export const growthPlan = [
  {
    label: "Current base",
    date: "Now",
    aum: 9_271_153.85,
    units: 55,
    note: "Stabilize the current four-property multifamily base and finish the 115th flip.",
  },
  {
    label: "Lucia refi",
    date: "July 2026",
    aum: 9_271_153.85,
    units: 55,
    note: "Use the refi lane to recycle cash while keeping lender assumptions separate from public AUM.",
  },
  {
    label: "Sun Cove refi",
    date: "August 2026",
    aum: 9_271_153.85,
    units: 55,
    note: "Convert rehab and lease-up into cash-out capacity.",
  },
  {
    label: "Year-end 2026 target",
    date: "December 2026",
    aum: 23_760_000,
    units: 124,
    note: "Target scenario from the 3-year model.",
  },
];

export const photoLibrary = {
  sunCoveBefore: [
    sunCoveExterior,
    "/attached_assets/gallery/sun-cove-apartments/before/21 unit cover photo .jpg",
    "/attached_assets/gallery/sun-cove-apartments/before/13 unit cover photo.jpg",
    "/attached_assets/gallery/sun-cove-apartments/before/8 unit cover photo .jpg",
    ...imgRange("/attached_assets/gallery/sun-cove-apartments/before", 838, 843),
    ...imgRange("/attached_assets/gallery/sun-cove-apartments/before", 845, 923),
  ],
  sunCoveAfter: [
    sunCoveAfter21,
    sunCoveAfter13,
    sunCoveAfter13One,
    sunCoveAfter13Two,
    sunCoveAfter13Three,
    sunCoveAfter13Four,
    sunCoveAfter8,
    sunCoveAfter8One,
  ],
  hickoryBefore: [
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 15, 18),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 79, 91),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 959, 961),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 9283, 9298),
  ],
  mlkBefore: [
    mlkExterior,
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 1579, 1583),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 1605, 1612),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 7227, 7231, "PNG"),
    "/attached_assets/gallery/mlk-apartments/before/IMG_7435.jpeg",
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 8063, 8066),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 8104, 8107),
    "/attached_assets/gallery/mlk-apartments/before/IMG_8110.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8110(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8111.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8111(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8112.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8112(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8224.jpeg",
  ],
  mlkAfter: [
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8035, 8046),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8074, 8081),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8330, 8332),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8336, 8341),
  ],
  luciaBefore: [
    luciaExterior,
    "/attached_assets/gallery/lucia-apartments/before/IMG_1722.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1723.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1724.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1729.jpeg",
  ],
  luciaAfter: [
    luciaAfterOne,
    luciaAfterTwo,
    luciaAfterThree,
    luciaAfterFour,
    luciaAfterFive,
  ],
};

export const publicCurrentProperties: Property[] = [
  property({
    id: "sun-cove-apartments",
    name: "Sun Cove Apartments",
    address: "5680 28th St N",
    city: "St. Petersburg",
    state: "FL",
    zipCode: "33714",
    units: 21,
    acquisitionDate: d("2025-01-15T00:00:00.000Z"),
    acquisitionPrice: money(2_000_000),
    rehabCosts: money(475_000),
    currentValue: money(3_846_153.85),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.35",
    noi: money(250_000),
    cashflow: money(50_409.25),
    currentDebt: money(2_004_839.64),
    totalBasis: money(2_475_000),
    stabilizedNOI: money(250_000),
    capRateStabilized: "0.0650",
    entryPerUnit: money(95_238),
    arvPerUnit: money(183_150.18),
    arvTotal: money(3_846_153.85),
    valueCreation: money(1_371_153.85),
    bridgeLoan: money(2_004_839.64),
    annualDebtService: money(199_590.75),
    yieldOnCost: "0.1010101",
    dscrStabilized: "1.2525631",
    debtYield: "0.1000",
    exitCapRate: "0.0650",
    totalUnits: 21,
    occupiedUnits: 13,
    occupancyRate: "0.6190476",
    inPlaceRent: money(18_190),
    proformaRent: money(32_600),
    rentUpside: money(14_410),
    refiLTV: "0.6500",
    refiLoanAmount: money(2_500_000),
    refiCashOut: money(385_636.86),
    newMonthlyPI: money(16_632.56),
    equityAfterRefi: money(1_346_153.85),
    beforePhotos: JSON.stringify(photoLibrary.sunCoveBefore),
    afterPhotos: JSON.stringify(photoLibrary.sunCoveAfter),
    phase: "lease_up",
    refiTarget: "Modeled lender scenario",
    investmentThesis: "Lease-up and refinance underwriting uses the approved lender case: $250,000 NOI at a 6.5% cap rate.",
  }),
  property({
    id: "lucia-apartments",
    name: "Lucia Apartments",
    address: "669 Avenue B NW",
    city: "Winter Haven",
    state: "FL",
    zipCode: "33881",
    units: 16,
    acquisitionDate: d("2025-02-15T00:00:00.000Z"),
    acquisitionPrice: money(1_320_000),
    rehabCosts: money(140_000),
    currentValue: money(2_200_000),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.25",
    noi: money(147_356.20),
    cashflow: money(12_991),
    currentDebt: money(1_439_000),
    totalBasis: money(1_460_000),
    stabilizedNOI: money(147_356.20),
    capRateStabilized: "0.0669801",
    entryPerUnit: money(82_500),
    arvPerUnit: money(137_500),
    arvTotal: money(2_200_000),
    valueCreation: money(740_000),
    bridgeLoan: money(1_439_000),
    monthlyPI: money(11_197.10),
    annualDebtService: money(134_365.20),
    yieldOnCost: "0.1009289",
    dscrStabilized: "1.0966843",
    debtYield: "0.1024018",
    exitCapRate: "0.0669801",
    totalUnits: 16,
    occupiedUnits: 13,
    occupancyRate: "0.8125",
    inPlaceRent: money(15_145),
    proformaRent: money(19_600),
    rentUpside: money(4_455),
    refiLTV: "0.6540909",
    refiLoanAmount: money(1_439_000),
    newMonthlyPI: money(11_197.10),
    equityAfterRefi: money(761_000),
    beforePhotos: JSON.stringify(photoLibrary.luciaBefore),
    afterPhotos: JSON.stringify(photoLibrary.luciaAfter),
    phase: "lease_up",
    refiTarget: "Lender package scenario",
    investmentThesis: "Winter Haven value-add underwriting uses the workbook's selected $147,356.20 annual NOI with current lease-up tracked separately.",
  }),
  property({
    id: "hickory-landing",
    name: "Hickory Landing",
    address: "2006 W Hickory St",
    city: "Lakeland",
    state: "FL",
    zipCode: "33815",
    units: 8,
    acquisitionDate: d("2024-04-01T00:00:00.000Z"),
    acquisitionPrice: money(665_000),
    rehabCosts: money(200_000),
    currentValue: money(1_250_000),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "2.15",
    noi: money(86_658.41),
    cashflow: money(32_878.72),
    currentDebt: money(782_250),
    totalBasis: money(865_000),
    stabilizedNOI: money(86_658.41),
    capRateStabilized: "0.0693267",
    entryPerUnit: money(83_125),
    arvPerUnit: money(156_250),
    arvTotal: money(1_250_000),
    valueCreation: money(385_000),
    bridgeLoan: money(782_250),
    monthlyPI: money(4_481.64),
    annualDebtService: money(53_779.69),
    yieldOnCost: "0.1001831",
    dscrStabilized: "1.6113594",
    debtYield: "0.1107810",
    exitCapRate: "0.0693267",
    totalUnits: 8,
    occupiedUnits: 5,
    occupancyRate: "0.6250",
    inPlaceRent: money(6_945),
    proformaRent: money(11_300),
    rentUpside: money(4_355),
    refiLTV: "0.6258",
    refiLoanAmount: money(782_250),
    refiCashOut: money(30_163.62),
    newMonthlyPI: money(4_481.64),
    equityAfterRefi: money(467_750),
    projectedSalePrice: money(1_453_900.70),
    beforePhotos: JSON.stringify(photoLibrary.hickoryBefore),
    afterPhotos: JSON.stringify([]),
    phase: "stabilizing",
    refiTarget: "Operating loan in place",
    investmentThesis: "Lakeland value-add asset with a $1.25 million operating value and a separate modeled exit case.",
  }),
  property({
    id: "mlk-apartments",
    name: "MLK Apartments",
    address: "3408 E Dr Martin Luther King Jr Blvd",
    city: "Tampa",
    state: "FL",
    zipCode: "33610",
    units: 10,
    acquisitionDate: d("2024-08-01T00:00:00.000Z"),
    acquisitionPrice: money(750_000),
    rehabCosts: money(450_000),
    currentValue: money(1_975_000),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.8",
    noi: money(131_654.93),
    cashflow: money(-16_545.07),
    currentDebt: money(1_235_000),
    totalBasis: money(1_200_000),
    stabilizedNOI: money(131_654.93),
    capRateStabilized: "0.0666607",
    entryPerUnit: money(75_000),
    arvPerUnit: money(197_500),
    arvTotal: money(1_975_000),
    valueCreation: money(775_000),
    bridgeLoan: money(1_235_000),
    monthlyPI: money(12_350),
    annualDebtService: money(148_200),
    yieldOnCost: "0.1097124",
    dscrStabilized: "0.8883599",
    debtYield: "0.1066032",
    exitCapRate: "0.0666607",
    totalUnits: 10,
    occupiedUnits: 8,
    occupancyRate: "0.8000",
    inPlaceRent: money(12_540),
    proformaRent: money(17_500),
    rentUpside: money(4_960),
    equityAfterRefi: money(740_000),
    beforePhotos: JSON.stringify(photoLibrary.mlkBefore),
    afterPhotos: JSON.stringify(photoLibrary.mlkAfter),
    phase: "lease_up",
    refiTarget: "No refinance modeled",
    investmentThesis: "Tampa lease-up underwriting uses $131,655 of annual NOI against the approved $1.975 million appraisal.",
  }),
];

export const publicFlipProject: Property = property({
  id: "115th-st-flip",
  name: "11169 115th St Flip",
  address: "11169 115th St",
  city: "Seminole",
  state: "FL",
  zipCode: "33772",
  units: 1,
  acquisitionDate: d("2026-03-09T00:00:00.000Z"),
  acquisitionPrice: money(402_500),
  rehabCosts: money(95_000),
  currentValue: money(575_000),
  salePrice: money(575_000),
  status: "current",
  ownershipStructure: "5Central public value",
  ownershipName: "5Central 115th LLC",
  yearsHeld: "0.58",
  irr: "69.8",
  equityMultiple: "1.70",
  totalBasis: money(497_500),
  totalProfit: money(50_837.01),
  projectedSalePrice: money(575_000),
  projectedNetProceeds: money(123_712.01),
  projectedTotalProfit: money(50_837.01),
  holdPeriodMonths: 7,
  beforePhotos: JSON.stringify([]),
  afterPhotos: JSON.stringify([]),
  initialCapitalRequired: money(72_875),
  cashOnCash: "69.76",
  totalReturnPercent: "69.76",
  phase: "active_flip",
  investmentThesis: "Single-family flip tracked beside the portfolio because it supports liquidity. Public view shows full project economics and does not show partner splits.",
});

export const publicSoldProperties: Property[] = [
  property({ id: "1-harmony-st", name: "1 Harmony St", address: "1 Harmony St", city: "Stonington", state: "CT", zipCode: "06378", units: 4, acquisitionDate: d("2024-11-01T00:00:00.000Z"), acquisitionPrice: money(1_050_000), rehabCosts: money(135_000), salePrice: money(1_250_000), saleDate: d("2025-01-15T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "1.25", irr: "12.50", equityMultiple: "1.08", totalBasis: money(1_115_000), totalCashflow: money(0), totalCashflowCollected: money(0), saleProceeds: money(162_500), totalProfit: money(12_500), profitPerUnit: money(3_125), initialCapitalRequired: money(150_000), cashOnCash: "0.00", totalReturnPercent: "8.33", appreciationPercent: "12.11", pricePerUnit: money(312_500), avgAnnualReturn: "6.67" }),
  property({ id: "41-stuart-ave", name: "41 Stuart Ave", address: "41 Stuart Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2020-05-01T00:00:00.000Z"), acquisitionPrice: money(195_000), rehabCosts: money(20_000), salePrice: money(365_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "4.00", irr: "85.00", equityMultiple: "14.15", totalBasis: money(215_000), totalCashflow: money(144_000), totalCashflowCollected: money(144_000), saleProceeds: money(159_000), totalProfit: money(283_000), profitPerUnit: money(94_333), initialCapitalRequired: money(20_000), cashOnCash: "180.00", totalReturnPercent: "1415.00", appreciationPercent: "69.77", pricePerUnit: money(121_667), avgAnnualReturn: "353.75" }),
  property({ id: "52-summit-ave", name: "52 Summit Ave", address: "52 Summit Ave", city: "New London", state: "CT", zipCode: "06320", units: 2, acquisitionDate: d("2022-07-01T00:00:00.000Z"), acquisitionPrice: money(315_000), rehabCosts: money(10_000), salePrice: money(375_000), saleDate: d("2025-01-20T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.50", irr: "48.00", equityMultiple: "3.10", totalBasis: money(325_000), totalCashflow: money(48_000), totalCashflowCollected: money(48_000), saleProceeds: money(75_000), totalProfit: money(93_000), profitPerUnit: money(46_500), initialCapitalRequired: money(30_000), cashOnCash: "64.00", totalReturnPercent: "310.00", appreciationPercent: "15.38", pricePerUnit: money(187_500), avgAnnualReturn: "124.00" }),
  property({ id: "29-brainard-st", name: "29 Brainard St", address: "29 Brainard St", city: "New London", state: "CT", zipCode: "06320", units: 1, acquisitionDate: d("2022-01-19T00:00:00.000Z"), acquisitionPrice: money(329_000), rehabCosts: money(0), salePrice: money(375_000), saleDate: d("2025-03-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "3.00", irr: "65.00", equityMultiple: "6.08", totalBasis: money(329_000), totalCashflow: money(30_000), totalCashflowCollected: money(30_000), saleProceeds: money(55_000), totalProfit: money(73_000), profitPerUnit: money(73_000), initialCapitalRequired: money(12_000), cashOnCash: "83.33", totalReturnPercent: "608.33", appreciationPercent: "13.98", pricePerUnit: money(375_000), avgAnnualReturn: "202.78" }),
  property({ id: "25-huntington-pl", name: "25 Huntington Pl", address: "25 Huntington Pl", city: "Norwich", state: "CT", zipCode: "06360", units: 1, acquisitionDate: d("2022-09-01T00:00:00.000Z"), acquisitionPrice: money(319_000), rehabCosts: money(0), salePrice: money(350_000), saleDate: d("2025-01-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "10.00", equityMultiple: "1.20", totalBasis: money(319_000), totalCashflow: money(36_000), totalCashflowCollected: money(36_000), saleProceeds: money(84_000), totalProfit: money(20_000), profitPerUnit: money(20_000), initialCapitalRequired: money(100_000), cashOnCash: "18.00", totalReturnPercent: "20.00", appreciationPercent: "9.72", pricePerUnit: money(350_000), avgAnnualReturn: "10.00", afterPhotos: JSON.stringify(["/properties/25-huntington-pl-detail.jpg"]) }),
  property({ id: "145-crystal-ave", name: "145 Crystal Ave", address: "145 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2022-11-01T00:00:00.000Z"), acquisitionPrice: money(210_000), rehabCosts: money(50_000), salePrice: money(325_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "28.00", equityMultiple: "1.57", totalBasis: money(260_000), totalCashflow: money(90_000), totalCashflowCollected: money(90_000), saleProceeds: money(80_000), totalProfit: money(61_500), profitPerUnit: money(20_500), initialCapitalRequired: money(108_500), cashOnCash: "41.47", totalReturnPercent: "56.68", appreciationPercent: "25.00", pricePerUnit: money(108_333), avgAnnualReturn: "28.34" }),
  property({ id: "149-crystal-ave", name: "149 Crystal Ave", address: "149 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2023-02-01T00:00:00.000Z"), acquisitionPrice: money(230_000), rehabCosts: money(50_000), salePrice: money(325_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "24.00", equityMultiple: "1.48", totalBasis: money(280_000), totalCashflow: money(90_000), totalCashflowCollected: money(90_000), saleProceeds: money(80_000), totalProfit: money(55_000), profitPerUnit: money(18_333), initialCapitalRequired: money(115_000), cashOnCash: "39.13", totalReturnPercent: "47.83", appreciationPercent: "16.07", pricePerUnit: money(108_333), avgAnnualReturn: "23.91" }),
  property({ id: "157-crystal-ave", name: "157 Crystal Ave", address: "157 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 5, acquisitionDate: d("2023-06-01T00:00:00.000Z"), acquisitionPrice: money(376_000), rehabCosts: money(10_000), salePrice: money(660_000), saleDate: d("2025-03-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.50", irr: "68.00", equityMultiple: "3.15", totalBasis: money(386_000), totalCashflow: money(87_000), totalCashflowCollected: money(87_000), saleProceeds: money(227_800), totalProfit: money(214_800), profitPerUnit: money(42_960), initialCapitalRequired: money(100_000), cashOnCash: "34.80", totalReturnPercent: "214.80", appreciationPercent: "70.98", pricePerUnit: money(132_000), avgAnnualReturn: "85.92" }),
  property({ id: "175-crystal-ave", name: "175 Crystal Ave", address: "175 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 2, acquisitionDate: d("2021-10-01T00:00:00.000Z"), acquisitionPrice: money(280_000), rehabCosts: money(0), salePrice: money(425_000), saleDate: d("2025-02-15T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "92.00", equityMultiple: "7.28", totalBasis: money(280_000), totalCashflow: money(97_000), totalCashflowCollected: money(97_000), saleProceeds: money(110_000), totalProfit: money(182_000), profitPerUnit: money(91_000), initialCapitalRequired: money(25_000), cashOnCash: "194.00", totalReturnPercent: "728.00", appreciationPercent: "51.79", pricePerUnit: money(212_500), avgAnnualReturn: "364.00" }),
  property({ id: "35-linden-st", name: "35 Linden St", address: "35 Linden St", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2022-11-01T00:00:00.000Z"), acquisitionPrice: money(385_000), rehabCosts: money(0), salePrice: money(440_000), saleDate: d("2025-01-10T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "35.00", equityMultiple: "1.84", totalBasis: money(385_000), totalCashflow: money(84_000), totalCashflowCollected: money(84_000), saleProceeds: money(122_500), totalProfit: money(94_000), profitPerUnit: money(31_333), initialCapitalRequired: money(112_500), cashOnCash: "37.33", totalReturnPercent: "83.56", appreciationPercent: "14.29", pricePerUnit: money(146_667), avgAnnualReturn: "41.78" }),
];

// Current flips now live in the unified-workbook-backed /flips ledger rather than
// the multifamily collection, which prevents the legacy single-project snapshot
// above from leaking stale modeled figures into portfolio totals or stories.
export const publicAllProperties = [...publicCurrentProperties, ...publicSoldProperties];

export const publicPropertyMeta: Record<string, PublicPropertyMeta> = {
  "sun-cove-apartments": {
    slug: "sun-cove-apartments",
    assetClass: "multifamily",
    cardImage: sunCoveExterior,
    publicStatus: "Active rehab and lease-up",
    shortThesis: "Finish units, lease up, and refinance the rent upside.",
    sourceNote: "Approved lender underwriting and the operating rent roll.",
    photoCount: photoLibrary.sunCoveBefore.length + photoLibrary.sunCoveAfter.length,
  },
  "lucia-apartments": {
    slug: "lucia-apartments",
    assetClass: "multifamily",
    cardImage: luciaExterior,
    publicStatus: "Active rehab and lease-up",
    shortThesis: "Winter Haven value-add with refinance work in motion.",
    sourceNote: "Approved underwriting and the operating rent roll.",
    photoCount: photoLibrary.luciaBefore.length + photoLibrary.luciaAfter.length,
  },
  "hickory-landing": {
    slug: "hickory-landing",
    assetClass: "multifamily",
    cardImage: "/attached_assets/gallery/hickory-landing/before/IMG_0961.jpeg",
    publicStatus: "Stabilizing, refi path active",
    shortThesis: "Tighten operations and finish refinance execution.",
    sourceNote: "Portfolio underwriting and the operating rent roll.",
    photoCount: photoLibrary.hickoryBefore.length,
  },
  "mlk-apartments": {
    slug: "mlk-apartments",
    assetClass: "multifamily",
    cardImage: mlkExterior,
    publicStatus: "Active lease-up",
    shortThesis: "Tampa execution story backed by the $1.975 million appraisal.",
    sourceNote: "Approved appraisal, underwriting, and operating rent roll.",
    photoCount: photoLibrary.mlkBefore.length + photoLibrary.mlkAfter.length,
  },
  "115th-st-flip": {
    slug: "115th-st-flip",
    assetClass: "single_family_flip",
    cardImage: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    publicStatus: "Active single-family flip",
    shortThesis: "Liquidity project. Full project profit is shown; partner splits are not shown.",
    sourceNote: "Portfolio Overview.xlsx, 115th Flip tab.",
    photoCount: 0,
  },
  "1-harmony-st": {
    slug: "1-harmony-st",
    assetClass: "sold",
    cardImage: "/properties/1-harmony-st.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "41-stuart-ave": {
    slug: "41-stuart-ave",
    assetClass: "sold",
    cardImage: "/properties/41-stuart-ave.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "52-summit-ave": {
    slug: "52-summit-ave",
    assetClass: "sold",
    cardImage: "/properties/52-summit-ave.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "29-brainard-st": {
    slug: "29-brainard-st",
    assetClass: "sold",
    cardImage: "/properties/29-brainard-st.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "25-huntington-pl": {
    slug: "25-huntington-pl",
    assetClass: "sold",
    cardImage: "/properties/25-huntington-pl.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 2,
  },
  "145-crystal-ave": {
    slug: "145-crystal-ave",
    assetClass: "sold",
    cardImage: "/properties/145-crystal-ave.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "149-crystal-ave": {
    slug: "149-crystal-ave",
    assetClass: "sold",
    cardImage: "/properties/149-crystal-ave.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "157-crystal-ave": {
    slug: "157-crystal-ave",
    assetClass: "sold",
    cardImage: "/157-crystal-ave.jpeg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "175-crystal-ave": {
    slug: "175-crystal-ave",
    assetClass: "sold",
    cardImage: "/175-crystal-ave.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
  "35-linden-st": {
    slug: "35-linden-st",
    assetClass: "sold",
    cardImage: "/properties/35-linden-st.jpg",
    publicStatus: "Sold",
    shortThesis: "Realized Connecticut exit.",
    sourceNote: "Historical property and exit records.",
    photoCount: 1,
  },
};

export const getPublicPropertyMeta = (property: Property) => publicPropertyMeta[property.id];

export const getPublicPropertyImage = (property: Property) =>
  getPublicPropertyMeta(property)?.cardImage || property.imageUrl || "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80";

export const publicPortfolioPulse = {
  cards: [
    { label: "Occupancy", value: "70.9%", sublabel: "39 of 55 units occupied" },
    { label: "In-place rent", value: "$52.8K/mo", sublabel: "Contracted base rent" },
    { label: "Underwritten rent", value: "$81.0K/mo", sublabel: "$28.2K monthly upside" },
    { label: "Underwritten NOI", value: "$615.7K/yr", sublabel: "Four-property total" },
  ],
};

export const dataRoomSections = [
  {
    title: "Lender package",
    items: ["Rent roll", "T-12 / P&L", "Debt schedule", "Insurance and entity docs"],
  },
  {
    title: "Property proof",
    items: ["Before / after photos", "Rehab scope", "Draw support", "Lease-up status"],
  },
  {
    title: "Investor reporting",
    items: ["Capital account", "Portfolio pulse", "Distribution history", "Source workbook extracts"],
  },
];
