import { type Property } from "@shared/schema";
import sunCoveExterior from "@assets/sun-cove-apartments.jpg";
import luciaExterior from "@assets/lucia-apartments.jpg";
import mlkExterior from "@assets/mlk-apartments.jpg";
import sunCoveAfter13 from "@assets/gallery/sun-cove-13-unit-cover-photo.jpg";
import sunCoveAfter13One from "@assets/gallery/sun-cove-13-unit-cover-photo-1.jpg";
import sunCoveAfter13Two from "@assets/gallery/sun-cove-13-unit-cover-photo-2.jpg";
import sunCoveAfter13Three from "@assets/gallery/sun-cove-13-unit-cover-photo-3.jpg";
import sunCoveAfter13Four from "@assets/gallery/sun-cove-13-unit-cover-photo-4.jpg";
import sunCoveAfter21 from "@assets/gallery/sun-cove-21-unit-cover-photo-.jpg";
import sunCoveAfter8 from "@assets/gallery/sun-cove-8-unit-cover-photo-.jpg";
import sunCoveAfter8One from "@assets/gallery/sun-cove-8-unit-cover-photo-1.jpg";
import luciaAfterOne from "@assets/gallery/lucia-1.jpg";
import luciaAfterTwo from "@assets/gallery/lucia-2.jpg";
import luciaAfterThree from "@assets/gallery/lucia-3.jpg";
import luciaAfterFour from "@assets/gallery/lucia-4.jpg";
import luciaAfterFive from "@assets/gallery/lucia-5.jpg";

const d = (value: string) => new Date(value);
const money = (value: number) => value.toFixed(2);

const imgRange = (prefix: string, start: number, end: number, ext = "jpeg") =>
  Array.from({ length: end - start + 1 }, (_, index) => `${prefix}/IMG_${String(start + index).padStart(4, "0")}.${ext}`);

const baseProperty: Property = {
  id: "",
  name: "",
  address: "",
  city: "",
  state: "FL",
  zipCode: "",
  units: 0,
  acquisitionDate: d("2024-01-01T00:00:00.000Z"),
  acquisitionPrice: "0.00",
  rehabCosts: "0.00",
  currentValue: null,
  salePrice: null,
  saleDate: null,
  totalCashflow: "0.00",
  status: "current",
  ownershipStructure: "5Central Capital",
  ownershipName: "5Central Capital",
  yearsHeld: null,
  irr: null,
  equityMultiple: null,
  noi: null,
  debtService: null,
  cashflow: null,
  currentDebt: null,
  refiDate: null,
  projectedSaleDate: null,
  imageUrl: null,
  yearBuilt: null,
  buildingSF: null,
  closingDate: null,
  investmentThesis: null,
  inPlaceNOI: null,
  stabilizedNOI: null,
  noiUpside: null,
  capRateInPlace: null,
  capRateStabilized: null,
  entryCapRate: null,
  exitCapRate: null,
  capRateSpread: null,
  valueCreation: null,
  entryPerUnit: null,
  exitPerUnit: null,
  arvPerUnit: null,
  arvTotal: null,
  bridgeLoan: null,
  ltvPurchase: null,
  ltc: null,
  interestRate: null,
  rehabHoldback: null,
  totalCommitment: null,
  monthlyPI: null,
  annualDebtService: null,
  maturityDate: null,
  loanType: null,
  irrLevered: null,
  moic: null,
  yieldOnCost: null,
  cashYieldStabilized: null,
  paybackPeriod: null,
  holdPeriod: null,
  refiMonth: null,
  sponsorEquity: null,
  breakevenOccupancy: null,
  dscrStabilized: null,
  debtYield: null,
  cashOutAtRefi: null,
  netCashFromSale: null,
  totalProfit: null,
  totalUnits: null,
  occupiedUnits: null,
  occupancyRate: null,
  inPlaceRent: null,
  proformaRent: null,
  rentUpside: null,
  refiLTV: null,
  refiLoanAmount: null,
  refiCashOut: null,
  newMonthlyPI: null,
  equityAfterRefi: null,
  refiTargetMonth: null,
  projectedSalePrice: null,
  projectedNetProceeds: null,
  projectedTotalProfit: null,
  holdPeriodMonths: null,
  beforePhotos: null,
  afterPhotos: null,
  initialCapitalRequired: null,
  totalCashflowCollected: null,
  saleProceeds: null,
  cashOnCash: null,
  totalReturnPercent: null,
  appreciationPercent: null,
  pricePerUnit: null,
  totalBasis: null,
  grossProfit: null,
  roc: null,
  avgAnnualReturn: null,
  profitPerUnit: null,
  phase: null,
  lender: null,
  refiTarget: null,
  monthlyRent: null,
  occupancyStatus: null,
};

const property = (input: Partial<Property> & Pick<Property, "id" | "name" | "address" | "city" | "state" | "zipCode" | "units" | "acquisitionDate" | "acquisitionPrice" | "status" | "ownershipStructure" | "ownershipName">): Property => ({
  ...baseProperty,
  ...input,
});

export interface PublicPropertyMeta {
  slug: string;
  assetClass: "multifamily" | "single_family_flip" | "sold";
  cardImage: string;
  publicStatus: string;
  shortThesis: string;
  sourceNote: string;
  photoCount?: number;
}

export const publicPortfolioFacts = {
  publicAum: 10_057_474,
  publicAumLabel: "$10.1M",
  publicAumNote: "Full public property value. This does not apply ownership discounts.",
  activeMultifamilyUnits: 55,
  activeMultifamilyAssets: 4,
  activeFlipProjects: 1,
  activeProjectCount: 5,
  rmSnapshotDate: "May 27, 2026",
  currentOccupancy: 0.6,
  occupiedUnits: 33,
  vacantUnits: 22,
  inPlaceMonthlyRent: 44_005.99,
  proformaMonthlyRent: 78_505,
  monthlyRentUpside: 34_499.01,
  projected2026Aum: 23_760_000,
  projected2026Units: 124,
  sourceWorkbook: "Portfolio Overview.xlsx",
};

export const growthPlan = [
  {
    label: "Current base",
    date: "Now",
    aum: 10_057_474,
    units: 55,
    note: "Stabilize the current four-property multifamily base and finish the 115th flip.",
  },
  {
    label: "Lucia refi",
    date: "July 2026",
    aum: 10_057_474,
    units: 55,
    note: "Use the refi lane to recycle cash while keeping lender assumptions separate from public AUM.",
  },
  {
    label: "Sun Cove refi",
    date: "August 2026",
    aum: 10_057_474,
    units: 55,
    note: "Convert rehab and lease-up into cash-out capacity.",
  },
  {
    label: "Year-end 2026 target",
    date: "December 2026",
    aum: 23_760_000,
    units: 124,
    note: "Target scenario from the 3-year model.",
  },
];

export const photoLibrary = {
  sunCoveBefore: [
    sunCoveExterior,
    "/attached_assets/gallery/sun-cove-apartments/before/21 unit cover photo .jpg",
    "/attached_assets/gallery/sun-cove-apartments/before/13 unit cover photo.jpg",
    "/attached_assets/gallery/sun-cove-apartments/before/8 unit cover photo .jpg",
    ...imgRange("/attached_assets/gallery/sun-cove-apartments/before", 838, 843),
    ...imgRange("/attached_assets/gallery/sun-cove-apartments/before", 845, 923),
  ],
  sunCoveAfter: [
    sunCoveAfter21,
    sunCoveAfter13,
    sunCoveAfter13One,
    sunCoveAfter13Two,
    sunCoveAfter13Three,
    sunCoveAfter13Four,
    sunCoveAfter8,
    sunCoveAfter8One,
  ],
  hickoryBefore: [
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 15, 18),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 79, 91),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 959, 961),
    ...imgRange("/attached_assets/gallery/hickory-landing/before", 9283, 9298),
  ],
  mlkBefore: [
    mlkExterior,
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 1579, 1583),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 1605, 1612),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 7227, 7231, "PNG"),
    "/attached_assets/gallery/mlk-apartments/before/IMG_7435.jpeg",
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 8063, 8066),
    ...imgRange("/attached_assets/gallery/mlk-apartments/before", 8104, 8107),
    "/attached_assets/gallery/mlk-apartments/before/IMG_8110.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8110(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8111.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8111(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8112.jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8112(1).jpeg",
    "/attached_assets/gallery/mlk-apartments/before/IMG_8224.jpeg",
  ],
  mlkAfter: [
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8035, 8046),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8074, 8081),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8330, 8332),
    ...imgRange("/attached_assets/gallery/mlk-apartments/after", 8336, 8341),
  ],
  luciaBefore: [
    luciaExterior,
    "/attached_assets/gallery/lucia-apartments/before/IMG_1722.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1723.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1724.jpeg",
    "/attached_assets/gallery/lucia-apartments/before/IMG_1729.jpeg",
  ],
  luciaAfter: [
    luciaAfterOne,
    luciaAfterTwo,
    luciaAfterThree,
    luciaAfterFour,
    luciaAfterFive,
  ],
};

export const publicCurrentProperties: Property[] = [
  property({
    id: "sun-cove-apartments",
    name: "Sun Cove Apartments",
    address: "5680 28th St N",
    city: "St. Petersburg",
    state: "FL",
    zipCode: "33714",
    units: 21,
    acquisitionDate: d("2025-01-15T00:00:00.000Z"),
    acquisitionPrice: money(2_000_000),
    rehabCosts: money(502_105),
    currentValue: money(4_200_000),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.35",
    irr: "44.0",
    irrLevered: "40-50%",
    equityMultiple: "5.30",
    noi: money(263_861),
    cashflow: money(27_376.7),
    currentDebt: money(2_102_105),
    totalBasis: money(2_477_105),
    inPlaceNOI: money(100_164),
    stabilizedNOI: money(263_861),
    noiUpside: money(163_697),
    entryPerUnit: money(95_238),
    arvTotal: money(4_200_000),
    valueCreation: money(1_722_895),
    bridgeLoan: money(1_600_000),
    ltvPurchase: "0.8000",
    interestRate: "0.1125",
    monthlyPI: money(19_707),
    annualDebtService: money(236_484),
    moic: "5.14",
    yieldOnCost: "0.1070",
    dscrStabilized: "1.56",
    debtYield: "0.0897",
    exitCapRate: "0.0628",
    totalProfit: money(1_331_584),
    totalUnits: 21,
    occupiedUnits: 11,
    occupancyRate: "0.5238",
    inPlaceRent: money(14_000),
    proformaRent: money(30_400),
    rentUpside: money(16_400),
    refiLTV: "0.7000",
    refiLoanAmount: money(2_940_000),
    refiCashOut: money(581_095),
    newMonthlyPI: money(15_500),
    equityAfterRefi: money(1_260_000),
    refiTargetMonth: 8,
    projectedSalePrice: money(4_200_000),
    projectedNetProceeds: money(1_092_000),
    projectedTotalProfit: money(1_331_584),
    holdPeriodMonths: 24,
    beforePhotos: JSON.stringify(photoLibrary.sunCoveBefore),
    afterPhotos: JSON.stringify(photoLibrary.sunCoveAfter),
    phase: "lease_up",
    refiTarget: "Q3 2026",
    investmentThesis: "Largest current value-add project. The work is simple: finish units, lease them, and convert the rent upside into refinance proceeds.",
  }),
  property({
    id: "lucia-apartments",
    name: "Lucia Apartments",
    address: "669 Avenue B NW",
    city: "Winter Haven",
    state: "FL",
    zipCode: "33881",
    units: 16,
    acquisitionDate: d("2025-02-15T00:00:00.000Z"),
    acquisitionPrice: money(1_320_000),
    rehabCosts: money(624_000),
    currentValue: money(2_587_662),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.25",
    irr: "42.0",
    irrLevered: "35-50%",
    equityMultiple: "6.70",
    noi: money(157_464),
    cashflow: money(-4_318.78),
    currentDebt: money(1_344_588),
    totalBasis: money(1_944_000),
    inPlaceNOI: money(80_520),
    stabilizedNOI: money(168_198),
    noiUpside: money(87_678),
    entryPerUnit: money(82_500),
    arvTotal: money(2_587_662),
    valueCreation: money(643_662),
    bridgeLoan: money(993_960),
    ltvPurchase: "0.7530",
    interestRate: "0.1125",
    monthlyPI: money(11_641),
    annualDebtService: money(139_692),
    moic: "2.15",
    yieldOnCost: "0.0870",
    dscrStabilized: "1.13",
    debtYield: "0.0921",
    exitCapRate: "0.0607",
    totalProfit: money(841_810),
    totalUnits: 16,
    occupiedUnits: 9,
    occupancyRate: "0.5625",
    inPlaceRent: money(10_260),
    proformaRent: money(19_555),
    rentUpside: money(9_295),
    refiLTV: "0.6590",
    refiLoanAmount: money(1_825_575),
    refiCashOut: money(480_987),
    newMonthlyPI: money(9_889),
    equityAfterRefi: money(946_413),
    refiTargetMonth: 7,
    projectedSalePrice: money(2_771_988),
    projectedNetProceeds: money(807_814),
    projectedTotalProfit: money(689_389),
    holdPeriodMonths: 24,
    beforePhotos: JSON.stringify(photoLibrary.luciaBefore),
    afterPhotos: JSON.stringify(photoLibrary.luciaAfter),
    phase: "lease_up",
    refiTarget: "Q2 2026",
    investmentThesis: "Winter Haven value-add with meaningful rent upside. The near-term job is lease-up, refinance readiness, and clean lender support.",
  }),
  property({
    id: "hickory-landing",
    name: "Hickory Landing",
    address: "2006 W Hickory St",
    city: "Lakeland",
    state: "FL",
    zipCode: "33815",
    units: 8,
    acquisitionDate: d("2024-04-01T00:00:00.000Z"),
    acquisitionPrice: money(665_000),
    rehabCosts: money(150_000),
    currentValue: money(1_294_812),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "2.15",
    irr: "44.0",
    irrLevered: "40-50%",
    equityMultiple: "1.59",
    noi: money(84_163),
    cashflow: money(7_410.8),
    currentDebt: money(682_000),
    totalBasis: money(815_000),
    inPlaceNOI: money(24_122),
    stabilizedNOI: money(84_163),
    noiUpside: money(60_041),
    entryPerUnit: money(83_125),
    arvTotal: money(1_294_812),
    valueCreation: money(479_812),
    bridgeLoan: money(532_000),
    ltvPurchase: "0.8000",
    interestRate: "0.1125",
    monthlyPI: money(6_396),
    annualDebtService: money(76_752),
    moic: "5.22",
    yieldOnCost: "0.1030",
    dscrStabilized: "1.63",
    debtYield: "0.0929",
    exitCapRate: "0.0650",
    totalProfit: money(527_028),
    totalUnits: 8,
    occupiedUnits: 7,
    occupancyRate: "0.8750",
    inPlaceRent: money(9_545.99),
    proformaRent: money(11_500),
    rentUpside: money(1_954.01),
    refiLTV: "0.7000",
    refiLoanAmount: money(906_368),
    refiCashOut: money(269_687),
    newMonthlyPI: money(5_700),
    equityAfterRefi: money(388_444),
    refiTargetMonth: 6,
    projectedSalePrice: money(1_294_812),
    projectedNetProceeds: money(336_000),
    projectedTotalProfit: money(527_028),
    holdPeriodMonths: 24,
    beforePhotos: JSON.stringify(photoLibrary.hickoryBefore),
    afterPhotos: JSON.stringify([]),
    phase: "stabilizing",
    refiTarget: "Q2 2026",
    investmentThesis: "Stabilized Lakeland asset with a straightforward refinance path and room to tighten operations.",
  }),
  property({
    id: "mlk-apartments",
    name: "MLK Apartments",
    address: "3408 E Dr Martin Luther King Jr Blvd",
    city: "Tampa",
    state: "FL",
    zipCode: "33610",
    units: 10,
    acquisitionDate: d("2024-08-01T00:00:00.000Z"),
    acquisitionPrice: money(750_000),
    rehabCosts: money(450_000),
    currentValue: money(1_975_000),
    status: "current",
    ownershipStructure: "5Central public value",
    ownershipName: "5Central Capital",
    yearsHeld: "1.8",
    irr: "44.0",
    irrLevered: "40-50%",
    equityMultiple: "1.58",
    noi: money(128_580),
    cashflow: money(51_396),
    currentDebt: money(1_235_000),
    totalBasis: money(1_200_000),
    inPlaceNOI: money(126_612),
    stabilizedNOI: money(128_580),
    noiUpside: money(1_968),
    entryPerUnit: money(75_000),
    arvTotal: money(1_975_000),
    valueCreation: money(775_000),
    bridgeLoan: money(600_000),
    ltvPurchase: "0.8000",
    interestRate: "0.0625",
    monthlyPI: money(6_432),
    annualDebtService: money(77_184),
    moic: "3.37",
    yieldOnCost: "0.1070",
    dscrStabilized: "1.66",
    debtYield: "0.0967",
    exitCapRate: "0.0677",
    totalProfit: money(527_175),
    totalUnits: 10,
    occupiedUnits: 6,
    occupancyRate: "0.6000",
    inPlaceRent: money(10_200),
    proformaRent: money(17_050),
    rentUpside: money(6_850),
    refiLTV: "0.7000",
    refiLoanAmount: money(1_330_000),
    refiCashOut: money(345_000),
    newMonthlyPI: money(8_300),
    equityAfterRefi: money(570_000),
    refiTargetMonth: 6,
    projectedSalePrice: money(1_900_000),
    projectedNetProceeds: money(589_000),
    projectedTotalProfit: money(527_175),
    holdPeriodMonths: 24,
    beforePhotos: JSON.stringify(photoLibrary.mlkBefore),
    afterPhotos: JSON.stringify(photoLibrary.mlkAfter),
    phase: "stabilized",
    refiTarget: "Q1 2026",
    investmentThesis: "Tampa asset with completed renovation proof and a refi/term-out lane. The public story is execution, not partner math.",
  }),
];

export const publicFlipProject: Property = property({
  id: "115th-st-flip",
  name: "11169 115th St Flip",
  address: "11169 115th St",
  city: "Seminole",
  state: "FL",
  zipCode: "33772",
  units: 1,
  acquisitionDate: d("2026-03-09T00:00:00.000Z"),
  acquisitionPrice: money(402_500),
  rehabCosts: money(95_000),
  currentValue: money(575_000),
  salePrice: money(575_000),
  status: "current",
  ownershipStructure: "5Central public value",
  ownershipName: "5Central 115th LLC",
  yearsHeld: "0.58",
  irr: "69.8",
  equityMultiple: "1.70",
  totalBasis: money(497_500),
  totalProfit: money(50_837.01),
  projectedSalePrice: money(575_000),
  projectedNetProceeds: money(123_712.01),
  projectedTotalProfit: money(50_837.01),
  holdPeriodMonths: 7,
  beforePhotos: JSON.stringify([]),
  afterPhotos: JSON.stringify([]),
  initialCapitalRequired: money(72_875),
  cashOnCash: "69.76",
  totalReturnPercent: "69.76",
  phase: "active_flip",
  investmentThesis: "Single-family flip tracked beside the portfolio because it supports liquidity. Public view shows full project economics and does not show partner splits.",
});

export const publicSoldProperties: Property[] = [
  property({ id: "1-harmony-st", name: "1 Harmony St", address: "1 Harmony St", city: "Stonington", state: "CT", zipCode: "06378", units: 4, acquisitionDate: d("2024-11-01T00:00:00.000Z"), acquisitionPrice: money(1_050_000), rehabCosts: money(135_000), salePrice: money(1_250_000), saleDate: d("2025-01-15T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "1.25", irr: "12.50", equityMultiple: "1.08", totalBasis: money(1_115_000), totalCashflow: money(0), totalCashflowCollected: money(0), saleProceeds: money(162_500), totalProfit: money(12_500), profitPerUnit: money(3_125), initialCapitalRequired: money(150_000), cashOnCash: "0.00", totalReturnPercent: "8.33", appreciationPercent: "12.11", pricePerUnit: money(312_500), avgAnnualReturn: "6.67" }),
  property({ id: "41-stuart-ave", name: "41 Stuart Ave", address: "41 Stuart Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2020-05-01T00:00:00.000Z"), acquisitionPrice: money(195_000), rehabCosts: money(20_000), salePrice: money(365_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "4.00", irr: "85.00", equityMultiple: "14.15", totalBasis: money(215_000), totalCashflow: money(144_000), totalCashflowCollected: money(144_000), saleProceeds: money(159_000), totalProfit: money(283_000), profitPerUnit: money(94_333), initialCapitalRequired: money(20_000), cashOnCash: "180.00", totalReturnPercent: "1415.00", appreciationPercent: "69.77", pricePerUnit: money(121_667), avgAnnualReturn: "353.75" }),
  property({ id: "52-summit-ave", name: "52 Summit Ave", address: "52 Summit Ave", city: "New London", state: "CT", zipCode: "06320", units: 2, acquisitionDate: d("2022-07-01T00:00:00.000Z"), acquisitionPrice: money(315_000), rehabCosts: money(10_000), salePrice: money(375_000), saleDate: d("2025-01-20T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.50", irr: "48.00", equityMultiple: "3.10", totalBasis: money(325_000), totalCashflow: money(48_000), totalCashflowCollected: money(48_000), saleProceeds: money(75_000), totalProfit: money(93_000), profitPerUnit: money(46_500), initialCapitalRequired: money(30_000), cashOnCash: "64.00", totalReturnPercent: "310.00", appreciationPercent: "15.38", pricePerUnit: money(187_500), avgAnnualReturn: "124.00" }),
  property({ id: "29-brainard-st", name: "29 Brainard St", address: "29 Brainard St", city: "New London", state: "CT", zipCode: "06320", units: 1, acquisitionDate: d("2022-01-19T00:00:00.000Z"), acquisitionPrice: money(329_000), rehabCosts: money(0), salePrice: money(375_000), saleDate: d("2025-03-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "3.00", irr: "65.00", equityMultiple: "6.08", totalBasis: money(329_000), totalCashflow: money(30_000), totalCashflowCollected: money(30_000), saleProceeds: money(55_000), totalProfit: money(73_000), profitPerUnit: money(73_000), initialCapitalRequired: money(12_000), cashOnCash: "83.33", totalReturnPercent: "608.33", appreciationPercent: "13.98", pricePerUnit: money(375_000), avgAnnualReturn: "202.78" }),
  property({ id: "25-huntington-pl", name: "25 Huntington Pl", address: "25 Huntington Pl", city: "Norwich", state: "CT", zipCode: "06360", units: 1, acquisitionDate: d("2022-09-01T00:00:00.000Z"), acquisitionPrice: money(319_000), rehabCosts: money(0), salePrice: money(350_000), saleDate: d("2025-01-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "10.00", equityMultiple: "1.20", totalBasis: money(319_000), totalCashflow: money(36_000), totalCashflowCollected: money(36_000), saleProceeds: money(84_000), totalProfit: money(20_000), profitPerUnit: money(20_000), initialCapitalRequired: money(100_000), cashOnCash: "18.00", totalReturnPercent: "20.00", appreciationPercent: "9.72", pricePerUnit: money(350_000), avgAnnualReturn: "10.00" }),
  property({ id: "145-crystal-ave", name: "145 Crystal Ave", address: "145 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2022-11-01T00:00:00.000Z"), acquisitionPrice: money(210_000), rehabCosts: money(50_000), salePrice: money(325_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "28.00", equityMultiple: "1.57", totalBasis: money(260_000), totalCashflow: money(90_000), totalCashflowCollected: money(90_000), saleProceeds: money(80_000), totalProfit: money(61_500), profitPerUnit: money(20_500), initialCapitalRequired: money(108_500), cashOnCash: "41.47", totalReturnPercent: "56.68", appreciationPercent: "25.00", pricePerUnit: money(108_333), avgAnnualReturn: "28.34" }),
  property({ id: "149-crystal-ave", name: "149 Crystal Ave", address: "149 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2023-02-01T00:00:00.000Z"), acquisitionPrice: money(230_000), rehabCosts: money(50_000), salePrice: money(325_000), saleDate: d("2025-02-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "24.00", equityMultiple: "1.48", totalBasis: money(280_000), totalCashflow: money(90_000), totalCashflowCollected: money(90_000), saleProceeds: money(80_000), totalProfit: money(55_000), profitPerUnit: money(18_333), initialCapitalRequired: money(115_000), cashOnCash: "39.13", totalReturnPercent: "47.83", appreciationPercent: "16.07", pricePerUnit: money(108_333), avgAnnualReturn: "23.91" }),
  property({ id: "157-crystal-ave", name: "157 Crystal Ave", address: "157 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 5, acquisitionDate: d("2023-06-01T00:00:00.000Z"), acquisitionPrice: money(376_000), rehabCosts: money(10_000), salePrice: money(660_000), saleDate: d("2025-03-01T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.50", irr: "68.00", equityMultiple: "3.15", totalBasis: money(386_000), totalCashflow: money(87_000), totalCashflowCollected: money(87_000), saleProceeds: money(227_800), totalProfit: money(214_800), profitPerUnit: money(42_960), initialCapitalRequired: money(100_000), cashOnCash: "34.80", totalReturnPercent: "214.80", appreciationPercent: "70.98", pricePerUnit: money(132_000), avgAnnualReturn: "85.92" }),
  property({ id: "175-crystal-ave", name: "175 Crystal Ave", address: "175 Crystal Ave", city: "New London", state: "CT", zipCode: "06320", units: 2, acquisitionDate: d("2021-10-01T00:00:00.000Z"), acquisitionPrice: money(280_000), rehabCosts: money(0), salePrice: money(425_000), saleDate: d("2025-02-15T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "92.00", equityMultiple: "7.28", totalBasis: money(280_000), totalCashflow: money(97_000), totalCashflowCollected: money(97_000), saleProceeds: money(110_000), totalProfit: money(182_000), profitPerUnit: money(91_000), initialCapitalRequired: money(25_000), cashOnCash: "194.00", totalReturnPercent: "728.00", appreciationPercent: "51.79", pricePerUnit: money(212_500), avgAnnualReturn: "364.00" }),
  property({ id: "35-linden-st", name: "35 Linden St", address: "35 Linden St", city: "New London", state: "CT", zipCode: "06320", units: 3, acquisitionDate: d("2022-11-01T00:00:00.000Z"), acquisitionPrice: money(385_000), rehabCosts: money(0), salePrice: money(440_000), saleDate: d("2025-01-10T00:00:00.000Z"), status: "sold", ownershipStructure: "Realized exit", ownershipName: "5Central Capital", yearsHeld: "2.00", irr: "35.00", equityMultiple: "1.84", totalBasis: money(385_000), totalCashflow: money(84_000), totalCashflowCollected: money(84_000), saleProceeds: money(122_500), totalProfit: money(94_000), profitPerUnit: money(31_333), initialCapitalRequired: money(112_500), cashOnCash: "37.33", totalReturnPercent: "83.56", appreciationPercent: "14.29", pricePerUnit: money(146_667), avgAnnualReturn: "41.78" }),
];

// Current flips now live in the unified-workbook-backed /flips ledger rather than
// the multifamily collection, which prevents the legacy single-project snapshot
// above from leaking stale modeled figures into portfolio totals or stories.
export const publicAllProperties = [...publicCurrentProperties, ...publicSoldProperties];

export const publicPropertyMeta: Record<string, PublicPropertyMeta> = {
  "sun-cove-apartments": {
    slug: "sun-cove-apartments",
    assetClass: "multifamily",
    cardImage: sunCoveExterior,
    publicStatus: "Active rehab and lease-up",
    shortThesis: "Finish units, lease up, and refinance the rent upside.",
    sourceNote: "Portfolio Overview.xlsx, public value and RM snapshot rows.",
    photoCount: photoLibrary.sunCoveBefore.length + photoLibrary.sunCoveAfter.length,
  },
  "lucia-apartments": {
    slug: "lucia-apartments",
    assetClass: "multifamily",
    cardImage: luciaExterior,
    publicStatus: "Active rehab and lease-up",
    shortThesis: "Winter Haven value-add with refinance work in motion.",
    sourceNote: "Portfolio Overview.xlsx and current public property data.",
    photoCount: photoLibrary.luciaBefore.length + photoLibrary.luciaAfter.length,
  },
  "hickory-landing": {
    slug: "hickory-landing",
    assetClass: "multifamily",
    cardImage: "/attached_assets/gallery/hickory-landing/before/IMG_0961.jpeg",
    publicStatus: "Stabilizing, refi path active",
    shortThesis: "Tighten operations and finish refinance execution.",
    sourceNote: "Portfolio Overview.xlsx, RM snapshot rows.",
    photoCount: photoLibrary.hickoryBefore.length,
  },
  "mlk-apartments": {
    slug: "mlk-apartments",
    assetClass: "multifamily",
    cardImage: mlkExterior,
    publicStatus: "Stabilized, term-out work active",
    shortThesis: "Tampa execution story with completed renovation proof.",
    sourceNote: "Portfolio Overview.xlsx and MLK gallery assets.",
    photoCount: photoLibrary.mlkBefore.length + photoLibrary.mlkAfter.length,
  },
  "115th-st-flip": {
    slug: "115th-st-flip",
    assetClass: "single_family_flip",
    cardImage: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    publicStatus: "Active single-family flip",
    shortThesis: "Liquidity project. Full project profit is shown; partner splits are not shown.",
    sourceNote: "Portfolio Overview.xlsx, 115th Flip tab.",
    photoCount: 0,
  },
};

export const getPublicPropertyMeta = (property: Property) => publicPropertyMeta[property.id];

export const getPublicPropertyImage = (property: Property) =>
  getPublicPropertyMeta(property)?.cardImage || property.imageUrl || "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80";

export const publicPortfolioPulse = {
  asOf: "May 27, 2026",
  cards: [
    { label: "Occupied", value: "33 / 55", sublabel: "60.0% current RM snapshot" },
    { label: "Rent upside", value: "$34.5K/mo", sublabel: "In-place to pro forma rent" },
    { label: "Active rehab", value: "Sun Cove + Lucia", sublabel: "Primary NOI creation" },
    { label: "Flip profit", value: "$50.8K", sublabel: "115th base case, full project profit" },
  ],
};

export const dataRoomSections = [
  {
    title: "Lender package",
    items: ["Rent roll", "T-12 / P&L", "Debt schedule", "Insurance and entity docs"],
  },
  {
    title: "Property proof",
    items: ["Before / after photos", "Rehab scope", "Draw support", "Lease-up status"],
  },
  {
    title: "Investor reporting",
    items: ["Capital account", "Portfolio pulse", "Distribution history", "Source workbook extracts"],
  },
];
