/**
 * Generate docs/company/mcp-inventory.md from the real MCP server with every
 * company service composed over a disposable synthetic database. The tool list,
 * annotations and descriptions are read from the live server, not hand-written.
 * Usage: npx tsx scripts/company/mcp-inventory.ts [--write]
 */
import { writeFileSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createRentOpsMcpServer } from "../../server/rent-ops/mcp/tools";
import { READ_SCOPE, WRITE_SCOPE } from "../../server/rent-ops/mcp/oauth";
import { RentOpsService } from "../../server/rent-ops/services/service";
import { createSyntheticRentOpsRepository } from "../../server/rent-ops/fixtures/synthetic";
import { createSyntheticCompanyDatabase, SYNTHETIC_COMPANY } from "../../server/company/testing/synthetic-database";
import { createCompanyServices } from "../../server/company/services";

export interface InventoryTool { name: string; description: string; readOnly: boolean; destructive: boolean; idempotent: boolean; openWorld: boolean }

export async function collectMcpInventory(): Promise<{ tools: InventoryTool[]; instructions: string | undefined; serverName: string | undefined }> {
  const database = await createSyntheticCompanyDatabase();
  try {
    const company = createCompanyServices(database.executor);
    const service = new RentOpsService(createSyntheticRentOpsRepository());
    const server = createRentOpsMcpServer(service, { subject: "inventory", scopes: [READ_SCOPE, WRITE_SCOPE] }, "https://5central.capital/mcp", {
      company, companyActorId: SYNTHETIC_COMPANY.actorId,
      billing: {} as never, accountAdmin: {} as never,
    });
    const client = new Client({ name: "inventory", version: "1" });
    const [a, b] = InMemoryTransport.createLinkedPair();
    await server.connect(a); await client.connect(b);
    const listed = await client.listTools();
    const info = client.getServerVersion();
    const instructions = client.getInstructions();
    await client.close(); await server.close();
    const tools = listed.tools.map(tool => ({
      name: tool.name,
      description: (tool.description ?? "").replace(/\s+/g, " ").trim(),
      readOnly: tool.annotations?.readOnlyHint === true,
      destructive: tool.annotations?.destructiveHint === true,
      idempotent: tool.annotations?.idempotentHint === true,
      openWorld: tool.annotations?.openWorldHint === true,
    })).sort((x, y) => x.name.localeCompare(y.name));
    return { tools, instructions, serverName: info?.name };
  } finally { await database.close(); }
}

export function renderMcpInventory(inventory: Awaited<ReturnType<typeof collectMcpInventory>>): string {
  const reads = inventory.tools.filter(tool => tool.readOnly).length;
  const lines = [
    "# 5Central Ops MCP tool inventory",
    "",
    "Generated by `npx tsx scripts/company/mcp-inventory.ts --write` from the running server with every company service composed. Do not edit by hand; `server/rent-ops/mcp/inventory.test.ts` fails when it drifts.",
    "",
    `Server: \`${inventory.serverName}\` · ${inventory.tools.length} tools (${reads} read, ${inventory.tools.length - reads} write). Endpoint: \`https://5central.capital/mcp\` (Streamable HTTP, OAuth). Start with \`get_ops_capabilities\`.`,
    "",
    "Server instructions:",
    "",
    `> ${inventory.instructions ?? ""}`,
    "",
    "| Tool | Kind | Idempotent | Destructive | Open world | Description |",
    "|---|---|---|---|---|---|",
    ...inventory.tools.map(tool => `| \`${tool.name}\` | ${tool.readOnly ? "read" : "write"} | ${tool.idempotent ? "yes" : "no"} | ${tool.destructive ? "yes" : "no"} | ${tool.openWorld ? "yes" : "no"} | ${tool.description.replaceAll("|", "\\|")} |`),
    "",
  ];
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const inventory = await collectMcpInventory();
  const markdown = renderMcpInventory(inventory);
  if (process.argv.includes("--write")) writeFileSync(new URL("../../docs/company/mcp-inventory.md", import.meta.url), markdown);
  else process.stdout.write(markdown);
  console.error(`${inventory.tools.length} tools`);
}
