import test from 'node:test';
import assert from 'node:assert/strict';
import { syntheticRentOpsSnapshot } from '../fixtures/synthetic';
import { TenantPaymentService } from './service';
import type { TenantPaymentStore } from './store';
import type { TenantPayment, ProcessorEvent, PaymentAdjustment, PaymentReceipt } from './model';
import type { TenantIdentity } from '../../../shared/tenant-portal-contracts';
import { normalizeStripeEvent } from './provider';
import Stripe from 'stripe';
function setup() {
 let snapshot=structuredClone(syntheticRentOpsSnapshot()); const t=snapshot.tenancies[0];snapshot.subsidyContracts=[];
 snapshot.ledgerTransactions=[{id:'rent',propertyId:t.propertyId,unitId:t.unitId,tenancyId:t.id,personId:t.primaryPersonId,kind:'charge',category:'base_rent',status:'posted',amountCents:10000,postedOn:'2026-09-01',dueOn:'2026-09-01',description:'Rent',payer:'tenant'}];snapshot.paymentAllocations=[];
 let payments:TenantPayment[]=[],adjustments:PaymentAdjustment[]=[],receipts:PaymentReceipt[]=[];let fail=false;
 const store:TenantPaymentStore={async transaction(work){const backup=structuredClone({snapshot,payments,adjustments,receipts});try{return await work(store);}catch(e){({snapshot,payments,adjustments,receipts}=backup);throw e;}},async lockTenancy(){},async snapshot(){return structuredClone(snapshot);},async list(id){return payments.filter(p=>p.tenancyId===id);},async findByRequest(account,id){return payments.find(p=>p.accountId===account&&p.requestId===id);},async findForEvent(e){return payments.find(p=>p.id===e.paymentId||!!e.paymentIntentId&&p.paymentIntentId===e.paymentIntentId);},async insert(p){payments.push(p);},async save(){},async hasEvent(id){return receipts.some(r=>r.id===id);},async receipt(r){receipts.push(r);},async adjustments(id){return adjustments.filter(a=>a.paymentId===id);},async adjustment(a){adjustments=adjustments.filter(x=>x.providerObjectId!==a.providerObjectId);adjustments.push(a);},async appendLedger(r){snapshot.ledgerTransactions.push(r);},async appendAllocation(a){if(fail)throw new Error('allocation failure');snapshot.paymentAllocations.push(a);}};
 const identity:TenantIdentity={id:'account',personId:t.primaryPersonId,tenancyId:t.id,email:'test@example.com',status:'active'};
 const service=new TenantPaymentService(store,{live:false,async createCheckout(){return {id:'cs_fake',url:'https://checkout.stripe.com/fake'};},verify(){throw new Error('bad signature');}},()=>new Date('2026-09-07T12:00:00Z'));
 return {service,identity,store,get snapshot(){return snapshot;},get payments(){return payments;},get receipts(){return receipts;},fail(){fail=true;},async checkout(){return service.checkout(identity,{tenancyId:t.id,amountCents:10000,requestId:'00000000-0000-4000-8000-000000000001'});}};
}
function success(paymentId:string,id='evt_success'):ProcessorEvent{return {id,type:'payment_intent.succeeded',created:100,live:false,state:'success',paymentId,paymentIntentId:'pi_fake',amountCents:10000,currency:'usd'};}
test('server rejects another tenancy and overpayment; pending is separate from ledger',async()=>{const s=setup();await assert.rejects(s.service.checkout(s.identity,{tenancyId:'other',amountCents:100,requestId:'00000000-0000-4000-8000-000000000001'}));await assert.rejects(s.service.checkout(s.identity,{tenancyId:s.identity.tenancyId,amountCents:10001,requestId:'00000000-0000-4000-8000-000000000001'}));await s.checkout();assert.equal(s.snapshot.ledgerTransactions.length,1);assert.equal((await s.service.list(s.identity)).accounts[0].pendingCents,10000);});
test('success retry credits once; refunds append reversal and residual payment',async()=>{const s=setup(),p=await s.checkout();await s.service.process(success(p.id));await s.service.process(success(p.id));await s.service.process(success(p.id,'evt_other_success'));assert.equal(s.snapshot.ledgerTransactions.length,2);assert.equal(s.snapshot.paymentAllocations.length,1);const refund:ProcessorEvent={id:'evt_refund',type:'refund.updated',created:101,live:false,state:'adjustment',paymentIntentId:'pi_fake',adjustment:{providerObjectId:'re_fake',kind:'refund',amountCents:2000,active:true,terminal:true}};await s.service.process(refund);await s.service.process({...refund,id:'evt_refund_retry'});assert.equal(s.snapshot.ledgerTransactions.length,4);assert.equal(s.payments[0].currentLedgerCents,8000);assert.equal(s.payments[0].status,'partially_refunded');});
test('allocation failure rolls back receipt and ledger posting atomically',async()=>{const s=setup(),p=await s.checkout();s.fail();await assert.rejects(s.service.process(success(p.id)));assert.equal(s.snapshot.ledgerTransactions.length,1);assert.equal(s.receipts.length,0);assert.equal(s.payments[0].status,'pending');});
test('unpaid checkout is processing, invalid signature cannot post',async()=>{const s=setup();await assert.rejects(s.service.webhook(Buffer.from('{}'),'invalid'));assert.equal(s.snapshot.ledgerTransactions.length,1);const event=normalizeStripeEvent({id:'evt',type:'checkout.session.completed',created:1,livemode:false,data:{object:{id:'cs',payment_status:'unpaid',amount_total:10000,currency:'usd'}}} as unknown as Stripe.Event);assert.equal(event.state,'processing');});
test('out of order confirmed refund before success is retained',async()=>{const s=setup(),p=await s.checkout();await s.service.process({id:'r',type:'refund.updated',created:200,live:false,state:'adjustment',paymentId:p.id,adjustment:{providerObjectId:'refund',kind:'refund',amountCents:10000,active:true,terminal:true}});await s.service.process(success(p.id));assert.equal(s.snapshot.ledgerTransactions.length,1);assert.equal(s.payments[0].status,'refunded');});
test('late ACH return dispute reverses credit, won restores once, stale open is ignored',async()=>{const s=setup(),p=await s.checkout();await s.service.process(success(p.id));const dispute:ProcessorEvent={id:'d1',type:'charge.dispute.created',created:201,live:false,state:'adjustment',paymentIntentId:'pi_fake',adjustment:{providerObjectId:'dp_fake',kind:'dispute',amountCents:10000,active:true,terminal:false}};await s.service.process(dispute);assert.equal(s.payments[0].currentLedgerCents,0);assert.equal(s.snapshot.ledgerTransactions.length,3);await s.service.process({...dispute,id:'d2',created:202,adjustment:{...dispute.adjustment!,active:false,terminal:true}});await s.service.process({...dispute,id:'d_stale'});assert.equal(s.payments[0].currentLedgerCents,10000);assert.equal(s.snapshot.ledgerTransactions.length,4);});
test('unlinked person ledger prevents checkout',async()=>{const s=setup();s.snapshot.ledgerTransactions.push({...s.snapshot.ledgerTransactions[0],id:'uncertain',tenancyId:null,tenancyLinkKnowledge:'unknown'});await assert.rejects(s.checkout(),/balance_review_required/);});
test('success cannot be undone by stale earlier payment attempt failure',async()=>{const s=setup(),p=await s.checkout();await s.service.process(success(p.id));await s.service.process({...success(p.id,'old_failure'),created:99,state:'failed',type:'payment_intent.payment_failed'});assert.equal(s.payments[0].currentLedgerCents,10000);assert.equal(s.payments[0].status,'posted');});
test('real Stripe signature verification accepts exact raw bytes and rejects tampering',async()=>{const {stripeProvider}=await import('./provider');const provider=stripeProvider({STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_fake',RENT_OPS_PUBLIC_APP_URL:'https://example.com'})!;const stripe=new Stripe('sk_test_fake');const body=JSON.stringify({id:'evt_signed',type:'payment_intent.succeeded',created:100,livemode:false,data:{object:{id:'pi',metadata:{tenantPaymentId:'tp'},amount_received:10000,currency:'usd'}}});const signature=stripe.webhooks.generateTestHeaderString({payload:body,secret:'whsec_fake'});assert.equal((await provider.verify(Buffer.from(body),signature)).state,'success');await assert.rejects(async()=>provider.verify(Buffer.from(body+' '),signature));assert.equal(stripeProvider({STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_fake',RENT_OPS_PUBLIC_APP_URL:'invalid'}),undefined);});
