import { createHash } from "node:crypto";
import type { TimeConnectionScope } from "../../shared/time";
import type { QuickBooksTimeOAuthTokenSet } from "./provider";
import type { RentOpsQueryExecutor } from "../rent-ops/repositories/postgres";
import { AccountingError } from "../accounting/errors";
import type { TimeEncryptedValue, TimeTokenCipher } from "./token-crypto";

export interface StoredTimeToken extends QuickBooksTimeOAuthTokenSet { readonly version: number; readonly updatedAt: string; }
export interface TimeTokenRepository { load(scope: TimeConnectionScope): Promise<StoredTimeToken | null>; save(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet, expectedVersion?: number): Promise<StoredTimeToken>; saveWithLease?(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet, expectedVersion: number, leaseOwnerId: string): Promise<StoredTimeToken>; saveNewConnection(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet): Promise<StoredTimeToken>; revoke(scope: TimeConnectionScope): Promise<void>; }
function scopeParts(scope: TimeConnectionScope): unknown[] { return [scope.organizationId, scope.legalEntityId, scope.environment, scope.providerCompanyId]; }
function text(value: unknown, field: string): string { if (typeof value !== "string" || value.length === 0) throw new AccountingError("accounting_unavailable", `Time token storage returned an invalid ${field}`); return value; }
function hashToken(value: string): string { return createHash("sha256").update(value).digest("hex"); }

class PostgresTimeTokenRepository implements TimeTokenRepository {
  constructor(private readonly executor: RentOpsQueryExecutor, private readonly cipher: TimeTokenCipher, private readonly now: () => Date = () => new Date()) {}
  async load(scope: TimeConnectionScope): Promise<StoredTimeToken | null> {
    const result = await this.executor.query<Record<string, unknown>>(`SELECT access_token_ciphertext,access_token_iv,access_token_auth_tag,refresh_token_ciphertext,refresh_token_iv,refresh_token_auth_tag,token_type,access_token_expires_at,refresh_token_expires_at,token_version,updated_at FROM time_connections WHERE organization_id=$1 AND legal_entity_id=$2 AND environment=$3 AND provider_company_id=$4 AND status='active'`, scopeParts(scope));
    const row = result.rows[0]; if (!row) return null;
    const encrypted = (prefix: "access_token" | "refresh_token"): TimeEncryptedValue => { const ciphertext = row[`${prefix}_ciphertext`]; const iv = row[`${prefix}_iv`]; const authTag = row[`${prefix}_auth_tag`]; if (!Buffer.isBuffer(ciphertext) || !Buffer.isBuffer(iv) || !Buffer.isBuffer(authTag)) throw new AccountingError("accounting_configuration", "QuickBooks Time encrypted token record is incomplete"); return { ciphertext, iv, authTag }; };
    const accessToken = this.cipher.decrypt(encrypted("access_token"), scope); const refreshToken = this.cipher.decrypt(encrypted("refresh_token"), scope); const version = typeof row.token_version === "number" ? row.token_version : Number(row.token_version); if (!Number.isSafeInteger(version) || version < 1) throw new AccountingError("accounting_unavailable", "QuickBooks Time token version is invalid");
    return { accessToken, refreshToken, tokenType: "bearer", accessTokenExpiresAt: text(row.access_token_expires_at instanceof Date ? row.access_token_expires_at.toISOString() : row.access_token_expires_at, "access token expiry"), ...(row.refresh_token_expires_at ? { refreshTokenExpiresAt: row.refresh_token_expires_at instanceof Date ? row.refresh_token_expires_at.toISOString() : String(row.refresh_token_expires_at) } : {}), version, updatedAt: text(row.updated_at instanceof Date ? row.updated_at.toISOString() : row.updated_at, "updated timestamp") };
  }
  async save(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet, expectedVersion?: number): Promise<StoredTimeToken> { return this.saveInternal(scope, token, expectedVersion, false); }
  async saveWithLease(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet, expectedVersion: number, leaseOwnerId: string): Promise<StoredTimeToken> {
    if (typeof leaseOwnerId !== "string" || !/^[A-Za-z0-9_.:-]{1,160}$/.test(leaseOwnerId)) throw new AccountingError("accounting_validation", "QuickBooks Time refresh lease owner is invalid");
    return this.saveInternal(scope, token, expectedVersion, false, leaseOwnerId);
  }
  async saveNewConnection(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet): Promise<StoredTimeToken> { return this.saveInternal(scope, token, undefined, true); }
  private async saveInternal(scope: TimeConnectionScope, token: QuickBooksTimeOAuthTokenSet, expectedVersion: number | undefined, allowReconnect: boolean, leaseOwnerId?: string): Promise<StoredTimeToken> {
    const access = this.cipher.encrypt(token.accessToken, scope); const refresh = this.cipher.encrypt(token.refreshToken, scope); const leasePredicate = leaseOwnerId ? "AND EXISTS (SELECT 1 FROM time_refresh_leases WHERE organization_id=$1 AND legal_entity_id=$2 AND environment=$3 AND provider_company_id=$4 AND owner_id=$15 AND lease_until>$16)" : ""; const values: unknown[] = [...scopeParts(scope), expectedVersion ?? null, access.ciphertext, access.iv, access.authTag, refresh.ciphertext, refresh.iv, refresh.authTag, token.tokenType, token.accessTokenExpiresAt, token.refreshTokenExpiresAt ?? null, ...(leaseOwnerId ? [leaseOwnerId, this.now().toISOString()] : [])]; const result = await this.executor.query<Record<string, unknown>>(`UPDATE time_connections SET status='active',access_token_ciphertext=$6,access_token_iv=$7,access_token_auth_tag=$8,refresh_token_ciphertext=$9,refresh_token_iv=$10,refresh_token_auth_tag=$11,token_type=$12,access_token_expires_at=$13,refresh_token_expires_at=$14,token_version=token_version+1,revoked_at=NULL,connected_at=COALESCE(connected_at,now()),updated_at=now() WHERE organization_id=$1 AND legal_entity_id=$2 AND environment=$3 AND provider_company_id=$4 AND status='active' AND ($5::bigint IS NULL OR token_version=$5) ${leasePredicate} RETURNING token_version,updated_at`, values);
    if (result.rows[0]) return { ...token, version: Number(result.rows[0].token_version), updatedAt: result.rows[0].updated_at instanceof Date ? result.rows[0].updated_at.toISOString() : String(result.rows[0].updated_at) };
    if (!allowReconnect) throw new AccountingError("accounting_conflict", "QuickBooks Time token version or active connection changed", { reason: "time_token_version_conflict" });
    const insert = await this.executor.query<Record<string, unknown>>(`INSERT INTO time_connections (id,organization_id,legal_entity_id,environment,provider_company_id,status,access_token_ciphertext,access_token_iv,access_token_auth_tag,refresh_token_ciphertext,refresh_token_iv,refresh_token_auth_tag,token_type,access_token_expires_at,refresh_token_expires_at,provider_scopes,connected_at) VALUES (gen_random_uuid(),$1,$2,$3,$4,'active',$5,$6,$7,$8,$9,$10,$11,$12,$13,'{}',now()) ON CONFLICT (organization_id,legal_entity_id,environment,provider_company_id) DO UPDATE SET status='active',access_token_ciphertext=EXCLUDED.access_token_ciphertext,access_token_iv=EXCLUDED.access_token_iv,access_token_auth_tag=EXCLUDED.access_token_auth_tag,refresh_token_ciphertext=EXCLUDED.refresh_token_ciphertext,refresh_token_iv=EXCLUDED.refresh_token_iv,refresh_token_auth_tag=EXCLUDED.refresh_token_auth_tag,token_type=EXCLUDED.token_type,access_token_expires_at=EXCLUDED.access_token_expires_at,refresh_token_expires_at=EXCLUDED.refresh_token_expires_at,revoked_at=NULL,token_version=time_connections.token_version+1,updated_at=now() RETURNING token_version,updated_at`, [...scopeParts(scope), access.ciphertext, access.iv, access.authTag, refresh.ciphertext, refresh.iv, refresh.authTag, token.tokenType, token.accessTokenExpiresAt, token.refreshTokenExpiresAt ?? null]); const row = insert.rows[0]; if (!row) throw new AccountingError("accounting_unavailable", "QuickBooks Time token could not be saved"); return { ...token, version: Number(row.token_version), updatedAt: row.updated_at instanceof Date ? row.updated_at.toISOString() : String(row.updated_at) };
  }
  async revoke(scope: TimeConnectionScope): Promise<void> { await this.executor.query(`UPDATE time_connections SET status='revoked',access_token_ciphertext=NULL,access_token_iv=NULL,access_token_auth_tag=NULL,refresh_token_ciphertext=NULL,refresh_token_iv=NULL,refresh_token_auth_tag=NULL,revoked_at=now(),updated_at=now() WHERE organization_id=$1 AND legal_entity_id=$2 AND environment=$3 AND provider_company_id=$4`, scopeParts(scope)); }
}
export function createTimeTokenRepository(executor: RentOpsQueryExecutor, cipher: TimeTokenCipher, now?: () => Date): TimeTokenRepository { return new PostgresTimeTokenRepository(executor, cipher, now); }
export function tokenFingerprint(token: QuickBooksTimeOAuthTokenSet): string { return hashToken(token.refreshToken); }
