import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  integer,
  index,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";

/**
 * PostgreSQL tables for the bounded Rent Operations module. The module keeps
 * posted financial facts append-only at the service boundary; the table
 * definitions intentionally expose reversal links instead of delete helpers.
 * Amounts are integer cents to avoid decimal arithmetic in the domain/API.
 */

const id = (name: string) => varchar(name, { length: 160 });
const money = (name: string) => integer(name);
const metadata = () => jsonb("metadata").$type<Record<string, unknown>>();

export const rentOpsSchemaMeta = pgTable("rent_ops_schema_meta", {
  version: integer("version").primaryKey(),
  checksumSha256: varchar("checksum_sha256", { length: 64 }),
  appliedAt: timestamp("applied_at", { withTimezone: true }).defaultNow().notNull(),
});

/** Immutable ordered migration ledger. v1's legacy meta row remains intact;
 * this additive ledger records every applied version and exact source digest. */
export const rentOpsSchemaMigrations = pgTable("rent_ops_schema_migrations", {
  version: integer("version").primaryKey(),
  checksumSha256: varchar("checksum_sha256", { length: 64 }).notNull(),
  appliedAt: timestamp("applied_at", { withTimezone: true }).defaultNow().notNull(),
  downSqlSha256: varchar("down_sql_sha256", { length: 64 }),
});

export const rentOpsProperties = pgTable("rent_ops_properties", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  name: text("name"),
  slug: varchar("slug", { length: 120 }).notNull(),
  addressLine1: text("address_line1"),
  addressLine2: text("address_line2"),
  city: text("city"),
  state: varchar("state", { length: 2 }),
  postalCode: varchar("postal_code", { length: 20 }),
  propertyType: text("property_type"),
  stateStatus: text("state_status"),
  operatingContact: text("operating_contact"),
  nameKnowledge: text("name_knowledge"),
  addressKnowledge: text("address_knowledge"),
  propertyTypeKnowledge: text("property_type_knowledge"),
  stateKnowledge: text("state_knowledge"),
  operatingContactKnowledge: text("operating_contact_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  slugUnique: uniqueIndex("rent_ops_properties_slug_unique").on(table.slug),
  sourceUnique: uniqueIndex("rent_ops_properties_source_unique").on(table.sourceSystem, table.sourceId),
}));

export const rentOpsUnits = pgTable("rent_ops_units", {
  id: id("id").primaryKey(),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  unitNumber: varchar("unit_number", { length: 80 }),
  unitType: text("unit_type"),
  bedrooms: integer("bedrooms"),
  bathrooms: real("bathrooms"),
  squareFeet: integer("square_feet"),
  marketRentCents: money("market_rent_cents"),
  defaultDepositCents: money("default_deposit_cents"),
  readiness: text("readiness"),
  listing: text("listing"),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitNumberKnowledge: text("unit_number_knowledge"),
  unitTypeKnowledge: text("unit_type_knowledge"),
  readinessKnowledge: text("readiness_knowledge"),
  listingKnowledge: text("listing_knowledge"),
  amenities: jsonb("amenities").$type<string[]>(),
  accessNotes: text("access_notes"),
  recordRevision: integer("record_revision").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  propertyUnitUnique: uniqueIndex("rent_ops_units_property_unit_unique").on(table.propertyId, table.unitNumber),
  sourceUnique: uniqueIndex("rent_ops_units_source_unique").on(table.sourceSystem, table.sourceId),
  propertyIndex: index("rent_ops_units_property_index").on(table.propertyId),
}));

export const rentOpsPeople = pgTable("rent_ops_people", {
  sourceAccountFacts: jsonb("source_account_facts").$type<Record<string, unknown>>(),
  id: id("id").primaryKey(),
  paymentReviewReason: text("payment_review_reason"),
  paymentReviewArtifactSha256: varchar("payment_review_artifact_sha256", { length: 64 }),
  paymentReviewSourceReference: text("payment_review_source_reference"),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email"),
  phone: text("phone"),
  phoneMethods: jsonb("phone_methods").$type<Array<Record<string, unknown>>>(),
  firstNameKnowledge: text("first_name_knowledge"),
  lastNameKnowledge: text("last_name_knowledge"),
  emailKnowledge: text("email_knowledge"),
  phoneKnowledge: text("phone_knowledge"),
  renterInsuranceExpiresOn: date("renter_insurance_expires_on"),
  archived: boolean("archived"),
  archivedKnowledge: text("archived_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_people_source_unique").on(table.sourceSystem, table.sourceId),
}));

export const rentOpsTenancies = pgTable("rent_ops_tenancies", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  primaryPersonId: id("primary_person_id").references(() => rentOpsPeople.id),
  status: text("status"),
  plannedMoveInOn: date("planned_move_in_on"),
  actualMoveInOn: date("actual_move_in_on"),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitLinkKnowledge: text("unit_link_knowledge"),
  primaryPersonLinkKnowledge: text("primary_person_link_knowledge"),
  statusKnowledge: text("status_knowledge"),
  plannedMoveInKnowledge: text("planned_move_in_knowledge"),
  noticeOn: date("notice_on"),
  expectedMoveOutOn: date("expected_move_out_on"),
  actualMoveOutOn: date("actual_move_out_on"),
  actualMoveInKnowledge: text("actual_move_in_knowledge"),
  noticeKnowledge: text("notice_knowledge"),
  expectedMoveOutKnowledge: text("expected_move_out_knowledge"),
  actualMoveOutKnowledge: text("actual_move_out_knowledge"),
  createdAtKnowledge: text("created_at_knowledge"),
  endedAtKnowledge: text("ended_at_knowledge"),
  applicationId: id("application_id"),
  createdAt: timestamp("created_at", { withTimezone: true }),
  endedAt: timestamp("ended_at", { withTimezone: true }),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_tenancies_source_unique").on(table.sourceSystem, table.sourceId),
  unitIndex: index("rent_ops_tenancies_unit_index").on(table.unitId),
}));

export const rentOpsHouseholdMemberships = pgTable("rent_ops_household_memberships", {
  id: id("id").primaryKey(),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  applicationId: id("application_id"),
  accountPersonId: id("account_person_id").references(() => rentOpsPeople.id),
  personId: id("person_id").notNull().references(() => rentOpsPeople.id),
  role: text("role"),
  relationship: text("relationship"),
  isFinanciallyResponsible: boolean("is_financially_responsible"),
  roleKnowledge: text("role_knowledge"),
  relationshipKnowledge: text("relationship_knowledge"),
  responsibilityKnowledge: text("responsibility_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  tenancyPersonUnique: uniqueIndex("rent_ops_household_tenancy_person_unique").on(table.tenancyId, table.personId),
}));

export const rentOpsLeaseTerms = pgTable("rent_ops_lease_terms", {
  id: id("id").primaryKey(),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  status: text("status"),
  contractStartOn: date("contract_start_on"),
  contractEndOn: date("contract_end_on"),
  monthToMonth: boolean("month_to_month"),
  signedOn: date("signed_on"),
  executedDocumentId: id("executed_document_id"),
  renewalOfId: id("renewal_of_id"),
  createdAt: timestamp("created_at", { withTimezone: true }),
  tenancyLinkKnowledge: text("tenancy_link_knowledge"),
  statusKnowledge: text("status_knowledge"),
  contractStartKnowledge: text("contract_start_knowledge"),
  contractEndKnowledge: text("contract_end_knowledge"),
  signedOnKnowledge: text("signed_on_knowledge"),
  monthToMonthKnowledge: text("month_to_month_knowledge"),
  createdAtKnowledge: text("created_at_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_lease_terms_source_unique").on(table.sourceSystem, table.sourceId),
  tenancyIndex: index("rent_ops_lease_terms_tenancy_index").on(table.tenancyId),
}));

/** Operational, opaque charge-definition identity.  Source labels/keys are
 * retained only in the restricted archive; this table carries safe display
 * metadata and exact semantic knowledge for reports. */
export const rentOpsChargeDefinitions = pgTable("rent_ops_charge_definitions", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  sourceArtifactSha256: varchar("source_artifact_sha256", { length: 64 }),
  artifactObservationOn: date("artifact_observation_on"),
  displayName: text("display_name"),
  displayNameKnowledge: text("display_name_knowledge"),
  category: text("category"),
  categoryKnowledge: text("category_knowledge"),
  active: boolean("active"),
  activeKnowledge: text("active_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_charge_definitions_source_unique").on(table.sourceSystem, table.sourceId, table.sourceArtifactSha256),
}));

/** Restricted exact semantic evidence.  It is intentionally not part of
 * rentOpsTables and therefore cannot be selected by browser repositories. */
export const rentOpsFinancialSemanticCrosswalks = pgTable("rent_ops_financial_semantic_crosswalks", {
  id: id("id").primaryKey(),
  artifactSha256: varchar("artifact_sha256", { length: 64 }).notNull(),
  sourceCollection: text("source_collection").notNull(),
  sourceField: text("source_field").notNull(),
  semanticKind: text("semantic_kind").notNull(),
  normalization: text("normalization").notNull(),
  normalizedValue: text("normalized_value").notNull(),
  targetValue: text("target_value").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  exactKeyUnique: uniqueIndex("rent_ops_financial_crosswalk_exact_unique").on(table.artifactSha256, table.sourceCollection, table.sourceField, table.semanticKind, table.normalization, table.normalizedValue),
}));

export const rentOpsRecurringChargeSchedules = pgTable("rent_ops_recurring_charge_schedules", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  scopeType: text("scope_type"),
  scopeId: id("scope_id"),
  scopeTypeKnowledge: text("scope_type_knowledge"),
  scopeLinkKnowledge: text("scope_link_knowledge"),
  chargeDefinitionId: id("charge_definition_id").references(() => rentOpsChargeDefinitions.id),
  chargeDefinitionKey: text("charge_definition_key"),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  personId: id("person_id").references(() => rentOpsPeople.id),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  category: text("category"),
  categoryKnowledge: text("category_knowledge"),
  description: text("description"),
  descriptionKnowledge: text("description_knowledge"),
  amountCents: money("amount_cents"),
  amountKnowledge: text("amount_knowledge"),
  effectiveFrom: date("effective_from"),
  effectiveFromKnowledge: text("effective_from_knowledge"),
  effectiveTo: date("effective_to"),
  active: boolean("active"),
  activeKnowledge: text("active_knowledge"),
  sourceConfidence: text("source_confidence"),
  chargeDefinitionKnowledge: text("charge_definition_knowledge"),
  chargeDefinitionLinkKnowledge: text("charge_definition_link_knowledge"),
  sourceArtifactSha256: varchar("source_artifact_sha256", { length: 64 }),
  artifactObservationOn: date("artifact_observation_on"),
  lineageRootId: id("lineage_root_id").notNull(),
  lineageRootOrigin: text("lineage_root_origin").notNull(),
  versionOrigin: text("version_origin").notNull(),
  supersedesId: id("supersedes_id"),
  versionAction: text("version_action").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_schedules_source_unique").on(table.sourceSystem, table.sourceId),
  tenancyDateIndex: index("rent_ops_schedules_tenancy_date_index").on(table.tenancyId, table.effectiveFrom, table.effectiveTo),
  lineageIndex: index("rent_ops_schedules_lineage_index").on(table.lineageRootId, table.effectiveFrom),
  predecessorUnique: uniqueIndex("rent_ops_schedules_predecessor_unique").on(table.supersedesId),
}));

export const rentOpsLedgerTransactions = pgTable("rent_ops_ledger_transactions", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  sourceUpdatedAt: timestamp("source_updated_at", {withTimezone:true}),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  personId: id("person_id").references(() => rentOpsPeople.id),
  kind: text("kind").notNull(),
  category: text("category"),
  categoryKnowledge: text("category_knowledge"),
  status: text("status"),
  amountCents: money("amount_cents"),
  postedOn: date("posted_on"),
  dueOn: date("due_on"),
  paymentMethod: text("payment_method"),
  paymentMethodKnowledge: text("payment_method_knowledge"),
  description: text("description"),
  reversalOfId: id("reversal_of_id"),
  payer: text("payer"),
  payerKnowledge: text("payer_knowledge"),
  adjustmentDirection: text("adjustment_direction"),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitLinkKnowledge: text("unit_link_knowledge"),
  tenancyLinkKnowledge: text("tenancy_link_knowledge"),
  personLinkKnowledge: text("person_link_knowledge"),
  amountKnowledge: text("amount_knowledge"),
  postedOnKnowledge: text("posted_on_knowledge"),
  dueOnKnowledge: text("due_on_knowledge"),
  descriptionKnowledge: text("description_knowledge"),
  statusKnowledge: text("status_knowledge"),
  allocationMode: text("allocation_mode"),
  chargeDefinitionId: id("charge_definition_id").references(() => rentOpsChargeDefinitions.id),
  chargeDefinitionLinkKnowledge: text("charge_definition_link_knowledge"),
  sourceArtifactSha256: varchar("source_artifact_sha256", { length: 64 }),
  artifactObservationOn: date("artifact_observation_on"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_ledger_source_unique").on(table.sourceSystem, table.sourceId),
  tenancyDateIndex: index("rent_ops_ledger_tenancy_date_index").on(table.tenancyId, table.postedOn),
}));

export const rentOpsPaymentAllocations = pgTable("rent_ops_payment_allocations", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  sourcePropertyId: id("source_property_id").references(()=>rentOpsProperties.id),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  kind: text("kind").notNull().default("allocation"),
  sourceArtifactSha256: text("source_artifact_sha256"),
  artifactObservationOn: date("artifact_observation_on"),
  creditTransactionId: id("credit_transaction_id").references(() => rentOpsLedgerTransactions.id),
  creditLinkKnowledge: text("credit_link_knowledge"),
  paymentTransactionId: id("payment_transaction_id").references(() => rentOpsLedgerTransactions.id),
  chargeTransactionId: id("charge_transaction_id").references(() => rentOpsLedgerTransactions.id),
  amountCents: money("amount_cents"),
  allocatedOn: date("allocated_on"),
  paymentLinkKnowledge: text("payment_link_knowledge"),
  chargeLinkKnowledge: text("charge_link_knowledge"),
  amountKnowledge: text("amount_knowledge"),
  allocatedOnKnowledge: text("allocated_on_knowledge"),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_allocations_source_unique").on(table.sourceSystem, table.sourceId),
  paymentChargeUnique: uniqueIndex("rent_ops_allocations_native_payment_charge_unique").on(table.paymentTransactionId, table.chargeTransactionId).where(sql`${table.sourceSystem} IS NULL`),
}));

export const rentOpsSecurityDeposits = pgTable("rent_ops_security_deposits", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  unitLinkKnowledge: text("unit_link_knowledge"),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  type: text("type"),
  typeKnowledge: text("type_knowledge"),
  amountHeldCents: money("amount_held_cents"),
  sourceBalanceCents: money("source_balance_cents"),
  receivedOn: date("received_on"),
  receivedOnKnowledge: text("received_on_knowledge"),
  dispositionStatus: text("disposition_status"),
  dispositionStatusKnowledge: text("disposition_status_knowledge"),
  disposedOn: date("disposed_on"),
  dispositionNotes: text("disposition_notes"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_deposits_source_unique").on(table.sourceSystem, table.sourceId),
}));

export const rentOpsSubsidyContracts = pgTable("rent_ops_subsidy_contracts", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  propertyId: id("property_id").notNull().references(() => rentOpsProperties.id),
  unitId: id("unit_id").notNull().references(() => rentOpsUnits.id),
  tenancyId: id("tenancy_id").notNull().references(() => rentOpsTenancies.id),
  agencyName: text("agency_name").notNull(),
  contractNumber: text("contract_number"),
  effectiveFrom: date("effective_from").notNull(),
  effectiveTo: date("effective_to"),
  agencyObligationCents: money("agency_obligation_cents").notNull(),
  tenantObligationCents: money("tenant_obligation_cents").notNull(),
  status: text("status"),
  statusKnowledge: text("status_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_subsidy_source_unique").on(table.sourceSystem, table.sourceId),
}));

/** Exact `/SubsidyTenants` child facts. Nullable links/facts are intentional:
 * the restricted source row must survive an unresolved operational join. */
export const rentOpsSubsidyTenants = pgTable("rent_ops_subsidy_tenants", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  subsidyContractId: id("subsidy_contract_id").references(() => rentOpsSubsidyContracts.id),
  subsidyContractLinkKnowledge: text("subsidy_contract_link_knowledge"),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  tenancyLinkKnowledge: text("tenancy_link_knowledge"),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  unitLinkKnowledge: text("unit_link_knowledge"),
  effectiveFrom: date("effective_from"),
  effectiveFromKnowledge: text("effective_from_knowledge"),
  effectiveTo: date("effective_to"),
  effectiveToKnowledge: text("effective_to_knowledge"),
  amountCents: money("amount_cents"),
  amountKnowledge: text("amount_knowledge"),
  payer: text("payer"),
  payerKnowledge: text("payer_knowledge"),
  status: text("status"),
  statusKnowledge: text("status_knowledge"),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_subsidy_tenants_source_unique").on(table.sourceSystem, table.sourceId),
  contractIndex: index("rent_ops_subsidy_tenants_contract_index").on(table.subsidyContractId),
}));

/** Exact `/SubsidyPayments` child facts. */
export const rentOpsSubsidyPayments = pgTable("rent_ops_subsidy_payments", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  subsidyContractId: id("subsidy_contract_id").references(() => rentOpsSubsidyContracts.id),
  subsidyContractLinkKnowledge: text("subsidy_contract_link_knowledge"),
  subsidyTenantId: id("subsidy_tenant_id").references(() => rentOpsSubsidyTenants.id),
  subsidyTenantLinkKnowledge: text("subsidy_tenant_link_knowledge"),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  tenancyLinkKnowledge: text("tenancy_link_knowledge"),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  unitLinkKnowledge: text("unit_link_knowledge"),
  paymentTransactionId: id("payment_transaction_id").references(() => rentOpsLedgerTransactions.id),
  paymentLinkKnowledge: text("payment_link_knowledge"),
  paymentOn: date("payment_on"),
  paymentOnKnowledge: text("payment_on_knowledge"),
  amountCents: money("amount_cents"),
  amountKnowledge: text("amount_knowledge"),
  payer: text("payer"),
  payerKnowledge: text("payer_knowledge"),
  status: text("status"),
  statusKnowledge: text("status_knowledge"),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_subsidy_payments_source_unique").on(table.sourceSystem, table.sourceId),
  contractIndex: index("rent_ops_subsidy_payments_contract_index").on(table.subsidyContractId),
  paymentIndex: index("rent_ops_subsidy_payments_payment_index").on(table.paymentTransactionId),
}));

export const rentOpsApplications = pgTable("rent_ops_applications", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  sourceType: text("source_type"),
  status: text("status"),
  email: text("email"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  phone: text("phone"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  submittedOn: date("submitted_on"),
  certificationAcceptedOn: date("certification_accepted_on"),
  resumeTokenHash: text("resume_token_hash"),
  resumeTokenExpiresAt: timestamp("resume_token_expires_at", { withTimezone: true }),
  convertedTenancyId: id("converted_tenancy_id").references(() => rentOpsTenancies.id),
  createdAt: timestamp("created_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  rentalHistory: jsonb("rental_history").$type<Record<string, unknown>>(),
  employment: jsonb("employment").$type<Record<string, unknown>>(),
  householdSummary: jsonb("household_summary").$type<Record<string, unknown>>(),
  preferences: jsonb("preferences").$type<Record<string, unknown>>(),
  voucher: jsonb("voucher").$type<Record<string, unknown>>(),
  pets: jsonb("pets").$type<Array<Record<string, unknown>>>(),
  vehicles: jsonb("vehicles").$type<Array<Record<string, unknown>>>(),
  emergencyContact: jsonb("emergency_contact").$type<Record<string, unknown>>(),
  profileAnswers: jsonb("profile_answers").$type<Record<string, unknown>>(),
  sourceTypeKnowledge: text("source_type_knowledge"),
  statusKnowledge: text("status_knowledge"),
  emailKnowledge: text("email_knowledge"),
  firstNameKnowledge: text("first_name_knowledge"),
  lastNameKnowledge: text("last_name_knowledge"),
  phoneKnowledge: text("phone_knowledge"),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitLinkKnowledge: text("unit_link_knowledge"),
  submittedOnKnowledge: text("submitted_on_knowledge"),
  certificationAcceptedOnKnowledge: text("certification_accepted_on_knowledge"),
  createdAtKnowledge: text("created_at_knowledge"),
  updatedAtKnowledge: text("updated_at_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_applications_source_unique").on(table.sourceSystem, table.sourceId),
  resumeHashUnique: uniqueIndex("rent_ops_applications_resume_hash_unique").on(table.resumeTokenHash),
  prospectLinkKnowledgeCheck: check("rent_ops_applications_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationHouseholdMembers = pgTable("rent_ops_application_household_members", {
  id: id("id").primaryKey(),
  applicationId: id("application_id").notNull().references(() => rentOpsApplications.id),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  relationship: text("relationship"),
  email: text("email"),
  phone: text("phone"),
  isMinor: boolean("is_minor").notNull().default(false),
});

export const rentOpsApplicationRequirements = pgTable("rent_ops_application_requirements", {
  id: id("id").primaryKey(),
  applicationId: id("application_id").notNull().references(() => rentOpsApplications.id),
  key: varchar("key", { length: 120 }).notNull(),
  label: text("label").notNull(),
  status: text("status").notNull().default("requested"),
  documentId: id("document_id").references(() => rentOpsApplicationHistoryDocuments.id),
  requestedOn: date("requested_on").notNull(),
  resolvedOn: date("resolved_on"),
}, (table) => ({
  applicationKeyUnique: uniqueIndex("rent_ops_application_requirements_key_unique").on(table.applicationId, table.key),
}));

/** Immutable v9 source-faithful prospect/application history tables. */
export const rentOpsProspects = pgTable("rent_ops_prospects", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  contactId: id("contact_id"),
  contactLinkKnowledge: text("contact_link_knowledge"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email"),
  phone: text("phone"),
  status: text("status"),
  statusKnowledge: text("status_knowledge").notNull(),
  createdOn: date("created_on"),
  createdOnKnowledge: text("created_on_knowledge").notNull(),
  updatedOn: date("updated_on"),
  updatedOnKnowledge: text("updated_on_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_prospects_source_unique").on(table.sourceSystem, table.sourceId),
  personLinkKnowledgeCheck: check("rent_ops_prospects_person_link_knowledge_check", sql`${table.personId} IS NULL OR ${table.personLinkKnowledge} IS NOT NULL`),
  contactLinkKnowledgeCheck: check("rent_ops_prospects_contact_link_knowledge_check", sql`${table.contactId} IS NULL OR ${table.contactLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationHistory = pgTable("rent_ops_application_history", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email"),
  phone: text("phone"),
  status: text("status"),
  statusKnowledge: text("status_knowledge").notNull(),
  submittedOn: date("submitted_on"),
  submittedOnKnowledge: text("submitted_on_knowledge").notNull(),
  createdOn: date("created_on"),
  createdOnKnowledge: text("created_on_knowledge").notNull(),
  updatedOn: date("updated_on"),
  updatedOnKnowledge: text("updated_on_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_history_source_unique").on(table.sourceSystem, table.sourceId),
  prospectIndex: index("rent_ops_application_history_prospect_index").on(table.prospectId),
  prospectLinkKnowledgeCheck: check("rent_ops_application_history_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  personLinkKnowledgeCheck: check("rent_ops_application_history_person_link_knowledge_check", sql`${table.personId} IS NULL OR ${table.personLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationInterests = pgTable("rent_ops_application_interests", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  unitLinkKnowledge: text("unit_link_knowledge"),
  sourceOrder: integer("source_order"),
  sourceRank: integer("source_rank"),
  preference: text("preference"),
  preferenceKnowledge: text("preference_knowledge").notNull(),
  interestedOn: date("interested_on"),
  interestedOnKnowledge: text("interested_on_knowledge").notNull(),
  rentCents: integer("rent_cents"),
  rentKnowledge: text("rent_knowledge").notNull(),
  bedrooms: integer("bedrooms"),
  bedroomsKnowledge: text("bedrooms_knowledge").notNull(),
  status: text("status"),
  statusKnowledge: text("status_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_interests_source_unique").on(table.sourceSystem, table.sourceId),
  applicationIndex: index("rent_ops_application_interests_application_index").on(table.applicationId, table.sourceOrder, table.sourceRank),
  prospectIndex: index("rent_ops_application_interests_prospect_index").on(table.prospectId, table.sourceOrder, table.sourceRank),
  prospectLinkKnowledgeCheck: check("rent_ops_application_interests_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_interests_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
  propertyLinkKnowledgeCheck: check("rent_ops_application_interests_property_link_knowledge_check", sql`${table.propertyId} IS NULL OR ${table.propertyLinkKnowledge} IS NOT NULL`),
  unitLinkKnowledgeCheck: check("rent_ops_application_interests_unit_link_knowledge_check", sql`${table.unitId} IS NULL OR ${table.unitLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationParticipants = pgTable("rent_ops_application_participants", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  personId: id("person_id").references(() => rentOpsPeople.id),
  personLinkKnowledge: text("person_link_knowledge"),
  sourceOrder: integer("source_order"),
  role: text("role"),
  roleKnowledge: text("role_knowledge").notNull(),
  relationship: text("relationship"),
  relationshipKnowledge: text("relationship_knowledge").notNull(),
  isMinor: boolean("is_minor"),
  minorKnowledge: text("minor_knowledge").notNull(),
  isFinanciallyResponsible: boolean("is_financially_responsible"),
  financialResponsibilityKnowledge: text("financial_responsibility_knowledge").notNull(),
  origin: text("origin").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_participants_source_unique").on(table.sourceSystem, table.sourceId),
  applicationIndex: index("rent_ops_application_participants_application_index").on(table.applicationId, table.sourceOrder),
  prospectIndex: index("rent_ops_application_participants_prospect_index").on(table.prospectId, table.sourceOrder),
  prospectLinkKnowledgeCheck: check("rent_ops_application_participants_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_participants_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
  personLinkKnowledgeCheck: check("rent_ops_application_participants_person_link_knowledge_check", sql`${table.personId} IS NULL OR ${table.personLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationRequirementOccurrences = pgTable("rent_ops_application_requirement_occurrences", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  key: text("key"),
  label: text("label"),
  status: text("status"),
  statusKnowledge: text("status_knowledge").notNull(),
  requestedOn: date("requested_on"),
  requestedOnKnowledge: text("requested_on_knowledge").notNull(),
  resolvedOn: date("resolved_on"),
  resolvedOnKnowledge: text("resolved_on_knowledge").notNull(),
  documentId: id("document_id"),
  documentLinkKnowledge: text("document_link_knowledge"),
  origin: text("origin").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_requirements_source_unique").on(table.sourceSystem, table.sourceId),
  prospectLinkKnowledgeCheck: check("rent_ops_application_requirements_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_requirements_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
  documentLinkKnowledgeCheck: check("rent_ops_application_requirements_document_link_knowledge_check", sql`${table.documentId} IS NULL OR ${table.documentLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationTemplateDefinitions = pgTable("rent_ops_application_template_definitions", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  name: text("name"),
  nameKnowledge: text("name_knowledge").notNull(),
  active: boolean("active"),
  activeKnowledge: text("active_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_template_definitions_source_unique").on(table.sourceSystem, table.sourceId),
}));

export const rentOpsApplicationTemplateSections = pgTable("rent_ops_application_template_sections", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  templateId: id("template_id").references(() => rentOpsApplicationTemplateDefinitions.id),
  templateLinkKnowledge: text("template_link_knowledge"),
  name: text("name"),
  nameKnowledge: text("name_knowledge").notNull(),
  sourceOrder: integer("source_order"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_template_sections_source_unique").on(table.sourceSystem, table.sourceId),
  templateLinkKnowledgeCheck: check("rent_ops_application_template_sections_template_link_knowledge_check", sql`${table.templateId} IS NULL OR ${table.templateLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationTemplateFields = pgTable("rent_ops_application_template_fields", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  templateId: id("template_id").references(() => rentOpsApplicationTemplateDefinitions.id),
  templateLinkKnowledge: text("template_link_knowledge"),
  sectionId: id("section_id").references(() => rentOpsApplicationTemplateSections.id),
  sectionLinkKnowledge: text("section_link_knowledge"),
  key: text("key"),
  label: text("label"),
  valueType: text("value_type"),
  sensitive: boolean("sensitive").notNull().default(false),
  sourceOrder: integer("source_order"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_template_fields_source_unique").on(table.sourceSystem, table.sourceId),
  templateLinkKnowledgeCheck: check("rent_ops_application_template_fields_template_link_knowledge_check", sql`${table.templateId} IS NULL OR ${table.templateLinkKnowledge} IS NOT NULL`),
  sectionLinkKnowledgeCheck: check("rent_ops_application_template_fields_section_link_knowledge_check", sql`${table.sectionId} IS NULL OR ${table.sectionLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationAnswerOccurrences = pgTable("rent_ops_application_answer_occurrences", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  fieldId: id("field_id").references(() => rentOpsApplicationTemplateFields.id),
  fieldLinkKnowledge: text("field_link_knowledge"),
  valueType: text("value_type").notNull(),
  safeValue: jsonb("safe_value"),
  valueKnowledge: text("value_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_answers_source_unique").on(table.sourceSystem, table.sourceId),
  applicationIndex: index("rent_ops_application_answers_application_index").on(table.applicationId),
  prospectIndex: index("rent_ops_application_answers_prospect_index").on(table.prospectId),
  prospectLinkKnowledgeCheck: check("rent_ops_application_answers_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_answers_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
  fieldLinkKnowledgeCheck: check("rent_ops_application_answers_field_link_knowledge_check", sql`${table.fieldId} IS NULL OR ${table.fieldLinkKnowledge} IS NOT NULL`),
  valueKnowledgeCheck: check("rent_ops_application_answers_value_knowledge_check", sql`${table.valueKnowledge} = 'known' OR ${table.safeValue} IS NULL`),
}));

export const rentOpsApplicationHistoryDocuments = pgTable("rent_ops_application_history_documents", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  type: text("type"),
  typeKnowledge: text("type_knowledge").notNull(),
  state: text("state"),
  stateKnowledge: text("state_knowledge").notNull(),
  fileName: text("file_name"),
  mimeType: text("mime_type"),
  metadataSizeBytes: integer("metadata_size_bytes"),
  metadataChecksumSha256: varchar("metadata_checksum_sha256", { length: 64 }),
  availability: text("availability").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_history_documents_source_unique").on(table.sourceSystem, table.sourceId),
  applicationIndex: index("rent_ops_application_history_documents_application_index").on(table.applicationId),
  prospectIndex: index("rent_ops_application_history_documents_prospect_index").on(table.prospectId),
  prospectLinkKnowledgeCheck: check("rent_ops_application_history_documents_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_history_documents_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
  availabilityMetadataOnlyCheck: check("rent_ops_application_history_documents_metadata_only_check", sql`${table.availability} IN ('metadata', 'unavailable')`),
}));

export const rentOpsApplicationHistoryActivities = pgTable("rent_ops_application_history_activities", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  applicationLinkKnowledge: text("application_link_knowledge"),
  type: text("type"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }),
  occurredAtKnowledge: text("occurred_at_knowledge").notNull(),
  actor: text("actor"),
  actorKnowledge: text("actor_knowledge").notNull(),
  summary: text("summary"),
  summaryKnowledge: text("summary_knowledge").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_application_history_activities_source_unique").on(table.sourceSystem, table.sourceId),
  applicationIndex: index("rent_ops_application_history_activities_application_index").on(table.applicationId, table.occurredAt),
  prospectIndex: index("rent_ops_application_history_activities_prospect_index").on(table.prospectId, table.occurredAt),
  prospectLinkKnowledgeCheck: check("rent_ops_application_history_activities_prospect_link_knowledge_check", sql`${table.prospectId} IS NULL OR ${table.prospectLinkKnowledge} IS NOT NULL`),
  applicationLinkKnowledgeCheck: check("rent_ops_application_history_activities_application_link_knowledge_check", sql`${table.applicationId} IS NULL OR ${table.applicationLinkKnowledge} IS NOT NULL`),
}));

export const rentOpsApplicationHistoryBlockers = pgTable("rent_ops_application_history_blockers", {
  id: id("id").primaryKey(),
  code: text("code").notNull(),
  applicationId: id("application_id").references(() => rentOpsApplicationHistory.id),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  occurrenceCount: integer("occurrence_count").notNull(),
  reason: text("reason").notNull(),
});

export const rentOpsApplicationHistoryAggregates = pgTable("rent_ops_application_history_aggregates", {
  id: id("id").primaryKey(),
  restrictedAnswerCount: integer("restricted_answer_count").notNull(),
  unmappedAnswerCount: integer("unmapped_answer_count").notNull(),
  missingAnswerApplications: integer("missing_answer_applications").notNull(),
  metadataOnlyDocumentCount: integer("metadata_only_document_count").notNull(),
  unavailableDocumentCount: integer("unavailable_document_count").notNull(),
  unlinkedActivityCount: integer("unlinked_activity_count").notNull(),
  unlinkedInterestCount: integer("unlinked_interest_count").notNull(),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  nonnegativeCountsCheck: check("rent_ops_application_history_aggregates_nonnegative_check", sql`${table.restrictedAnswerCount} >= 0 AND ${table.unmappedAnswerCount} >= 0 AND ${table.missingAnswerApplications} >= 0 AND ${table.metadataOnlyDocumentCount} >= 0 AND ${table.unavailableDocumentCount} >= 0 AND ${table.unlinkedActivityCount} >= 0 AND ${table.unlinkedInterestCount} >= 0`),
}));

export const rentOpsDocuments = pgTable("rent_ops_documents", {
  id: id("id").primaryKey(),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  personId: id("person_id").references(() => rentOpsPeople.id),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  applicationId: id("application_id").references(() => rentOpsApplications.id),
  historicalApplicationId: id("historical_application_id").references(() => rentOpsApplicationHistory.id),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  historicalApplicationLinkKnowledge: text("historical_application_link_knowledge"),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  type: text("type"),
  typeKnowledge: text("type_knowledge"),
  state: text("state").notNull().default("requested"),
  stateKnowledge: text("state_knowledge"),
  fileName: text("file_name"),
  mimeType: text("mime_type"),
  sizeBytes: integer("size_bytes"),
  checksumSha256: varchar("checksum_sha256", { length: 64 }),
  storageKey: text("storage_key"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  availability: text("availability"),
  storageKeyKnowledge: text("storage_key_knowledge"),
  metadataSizeBytes: integer("metadata_size_bytes"),
  metadataChecksumSha256: varchar("metadata_checksum_sha256", { length: 64 }),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_documents_source_unique").on(table.sourceSystem, table.sourceId),
  checksumIndex: index("rent_ops_documents_checksum_index").on(table.checksumSha256),
}));

export const rentOpsActivityEvents = pgTable("rent_ops_activity_events", {
  id: id("id").primaryKey(),
  propertyId: id("property_id").references(() => rentOpsProperties.id),
  unitId: id("unit_id").references(() => rentOpsUnits.id),
  personId: id("person_id").references(() => rentOpsPeople.id),
  tenancyId: id("tenancy_id").references(() => rentOpsTenancies.id),
  applicationId: id("application_id").references(() => rentOpsApplications.id),
  historicalApplicationId: id("historical_application_id").references(() => rentOpsApplicationHistory.id),
  prospectId: id("prospect_id").references(() => rentOpsProspects.id),
  historicalApplicationLinkKnowledge: text("historical_application_link_knowledge"),
  prospectLinkKnowledge: text("prospect_link_knowledge"),
  type: text("type"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }),
  actor: text("actor"),
  summary: text("summary"),
  detail: text("detail"),
  sourceSystem: text("source_system"),
  sourceId: text("source_id"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>(),
  occurredAtKnowledge: text("occurred_at_knowledge"),
  actorKnowledge: text("actor_knowledge"),
  summaryKnowledge: text("summary_knowledge"),
  typeKnowledge: text("type_knowledge"),
  propertyLinkKnowledge: text("property_link_knowledge"),
  unitLinkKnowledge: text("unit_link_knowledge"),
  personLinkKnowledge: text("person_link_knowledge"),
  tenancyLinkKnowledge: text("tenancy_link_knowledge"),
  applicationLinkKnowledge: text("application_link_knowledge"),
  recordRevision: integer("record_revision").notNull().default(1),
}, (table) => ({
  entityDateIndex: index("rent_ops_activity_entity_date_index").on(table.personId, table.occurredAt),
}));

export const rentOpsSourceRecords = pgTable("rent_ops_source_records", {
  id: id("id").primaryKey(),
  system: text("system").notNull(),
  entityType: text("entity_type").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  importedAt: timestamp("imported_at", { withTimezone: true }).defaultNow().notNull(),
  checksum: varchar("checksum", { length: 128 }),
  targetId: id("target_id").notNull(),
  rawMetadata: jsonb("raw_metadata").$type<Record<string, unknown>>(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_source_records_unique").on(table.system, table.entityType, table.sourceId),
}));

export const rentOpsImportRuns = pgTable("rent_ops_import_runs", {
  id: id("id").primaryKey(),
  system: text("system").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  mode: text("mode").notNull(),
  sourceManifestHash: varchar("source_manifest_hash", { length: 128 }),
  counts: jsonb("counts").$type<Record<string, number>>().notNull().default(sql`'{}'::jsonb`),
  exceptionCount: integer("exception_count").notNull().default(0),
  status: text("status").notNull().default("running"),
});

/** Redacted, append-only operator revision log. Values and provenance never
 * enter this table; it records affected field names only. */
export const rentOpsRecordChanges = pgTable("rent_ops_record_changes", {
  id: id("id").primaryKey(),
  entityType: varchar("entity_type", { length: 80 }).notNull(),
  targetId: id("target_id").notNull(),
  revision: integer("revision").notNull(),
  origin: varchar("origin", { length: 20 }).notNull(),
  actorSubject: varchar("actor_subject", { length: 160 }),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  changedFields: text("changed_fields").array().notNull(),
}, (table) => ({
  entityTypeValid: check("rent_ops_record_changes_entity_type_check", sql`${table.entityType} IN ('property','unit','person','household_membership','tenancy','lease_term','security_deposit','subsidy_contract','application','document','activity','recurring_schedule')`),
  revisionPositive: check("rent_ops_record_changes_revision_positive", sql`${table.revision} > 1`),
  adminActorRequired: check("rent_ops_record_changes_admin_actor_check", sql`${table.origin} <> 'admin' OR ${table.actorSubject} IS NOT NULL`),
  targetRevisionUnique: uniqueIndex("rent_ops_record_changes_target_revision_unique").on(table.entityType, table.targetId, table.revision),
  targetIndex: index("rent_ops_record_changes_target_index").on(table.entityType, table.targetId, table.occurredAt),
}));

/**
 * Restricted, lossless RM source archive. This table is intentionally omitted
 * from `rentOpsTables`, so the normal repository and every browser snapshot
 * have no code path to select raw tenant/application payloads.
 */
export const rentOpsSourcePayloads = pgTable("rent_ops_source_payloads", {
  id: id("id").primaryKey(),
  system: text("system").notNull(),
  sourceCollection: text("source_collection").notNull(),
  sourceId: text("source_id").notNull(),
  sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
  checksumSha256: varchar("checksum_sha256", { length: 64 }).notNull(),
  importRunId: id("import_run_id").notNull().references(() => rentOpsImportRuns.id),
  importedAt: timestamp("imported_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  versionUnique: uniqueIndex("rent_ops_source_payloads_version_unique").on(table.system, table.sourceCollection, table.sourceId, table.checksumSha256),
  importRunIndex: index("rent_ops_source_payloads_import_run_index").on(table.importRunId),
}));

/** Restricted metadata for source binaries stored outside PostgreSQL. */
export const rentOpsSourceBinaries = pgTable("rent_ops_source_binaries", {
  id: id("id").primaryKey(),
  system: text("system").notNull(),
  sourceCollection: text("source_collection").notNull(),
  sourceId: text("source_id").notNull(),
  importRunId: id("import_run_id").notNull().references(() => rentOpsImportRuns.id),
  storageKey: text("storage_key").notNull(),
  checksumSha256: varchar("checksum_sha256", { length: 64 }).notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  contentType: text("content_type"),
  verificationStatus: text("verification_status").notNull().default("verified"),
  importedAt: timestamp("imported_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  sourceUnique: uniqueIndex("rent_ops_source_binaries_source_unique").on(table.system, table.sourceCollection, table.sourceId, table.checksumSha256),
  importRunIndex: index("rent_ops_source_binaries_import_run_index").on(table.importRunId),
}));

/**
 * Server-only immutable binding for a verified document object.  It is kept
 * outside rentOpsTables so normal repository snapshots and browser DTOs never
 * select storage generations or restricted import linkage.
 */
export const rentOpsDocumentObjects = pgTable("rent_ops_document_objects", {
  documentId: id("document_id").primaryKey().references(() => rentOpsDocuments.id),
  bindingKind: text("binding_kind").notNull().default("applicant"),
  sourceBinaryId: id("source_binary_id").references(() => rentOpsSourceBinaries.id),
  importRunId: id("import_run_id").references(() => rentOpsImportRuns.id),
  sourceSystem: text("source_system"),
  sourceCollection: text("source_collection"),
  backend: text("backend").notNull(),
  logicalKey: text("logical_key").notNull(),
  checksumSha256: varchar("checksum_sha256", { length: 64 }).notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  immutableGeneration: text("immutable_generation"),
  immutableVersion: text("immutable_version"),
  verifiedAt: timestamp("verified_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const rentOpsTables = {
  schemaMeta: rentOpsSchemaMeta,
  schemaMigrations: rentOpsSchemaMigrations,
  properties: rentOpsProperties,
  units: rentOpsUnits,
  people: rentOpsPeople,
  tenancies: rentOpsTenancies,
  householdMemberships: rentOpsHouseholdMemberships,
  leaseTerms: rentOpsLeaseTerms,
  chargeDefinitions: rentOpsChargeDefinitions,
  recurringChargeSchedules: rentOpsRecurringChargeSchedules,
  ledgerTransactions: rentOpsLedgerTransactions,
  paymentAllocations: rentOpsPaymentAllocations,
  securityDeposits: rentOpsSecurityDeposits,
  subsidyContracts: rentOpsSubsidyContracts,
  subsidyTenants: rentOpsSubsidyTenants,
  subsidyPayments: rentOpsSubsidyPayments,
  applications: rentOpsApplications,
  applicationHouseholdMembers: rentOpsApplicationHouseholdMembers,
  applicationRequirements: rentOpsApplicationRequirements,
  prospects: rentOpsProspects,
  applicationHistory: rentOpsApplicationHistory,
  applicationInterests: rentOpsApplicationInterests,
  applicationParticipants: rentOpsApplicationParticipants,
  applicationRequirementOccurrences: rentOpsApplicationRequirementOccurrences,
  applicationTemplateDefinitions: rentOpsApplicationTemplateDefinitions,
  applicationTemplateSections: rentOpsApplicationTemplateSections,
  applicationTemplateFields: rentOpsApplicationTemplateFields,
  applicationAnswerOccurrences: rentOpsApplicationAnswerOccurrences,
  applicationHistoryDocuments: rentOpsApplicationHistoryDocuments,
  applicationHistoryActivities: rentOpsApplicationHistoryActivities,
  applicationHistoryBlockers: rentOpsApplicationHistoryBlockers,
  applicationHistoryAggregates: rentOpsApplicationHistoryAggregates,
  documents: rentOpsDocuments,
  activityEvents: rentOpsActivityEvents,
  sourceRecords: rentOpsSourceRecords,
  importRuns: rentOpsImportRuns,
  recordChanges: rentOpsRecordChanges,
};

export type RentOpsTableName = keyof typeof rentOpsTables;
