import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {syntheticRentOpsSnapshot} from '../server/rent-ops/fixtures/synthetic';
import {provisionImportedTenants,verifiedLeaseBytes,type RosterRow,type LeaseCandidate} from './provision-imported-tenants';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'provision-test-'));await mkdir(join(root,'files'));const bytes=Buffer.from('%PDF-1.7\nfixture\n%%EOF');await writeFile(join(root,'files/test.pdf'),bytes);const sha=createHash('sha256').update(bytes).digest('hex');
 const snapshot=syntheticRentOpsSnapshot(),t=snapshot.tenancies[0],person=snapshot.people.find(p=>p.id===t.primaryPersonId)!;person.source={system:'rent_manager',entityType:'person',sourceId:'873'};person.email='primary@example.test';Object.assign(t,{status:'current',statusKnowledge:'source',primaryPersonLinkKnowledge:'exact',propertyLinkKnowledge:'exact',unitLinkKnowledge:'exact'});snapshot.units.find(u=>u.id===t.unitId)!.propertyLinkKnowledge='exact';t.source={system:'rent_manager',entityType:'tenancy',sourceId:'lease:463'};snapshot.properties.find(p=>p.id===t.propertyId)!.source={system:'rent_manager',entityType:'property',sourceId:'30'};snapshot.units.find(u=>u.id===t.unitId)!.source={system:'rent_manager',entityType:'unit',sourceId:'179'};snapshot.sourceRecords.push({id:'cross',system:'rent_manager',entityType:'person',sourceId:'contact:884',targetId:person.id,importedAt:'2026-09-07T00:00:00Z'});
 const row:RosterRow={tenantId:873,primaryContactId:884,primaryEmail:person.email,status:'current',leases:[{leaseId:463,propertyId:30,unitId:179}],dateActiveLeaseIds:[463],provisioningBlockers:[]};
 const file:LeaseCandidate={packageRelativePath:'files/test.pdf',sourceTenantId:873,sourceLeaseId:463,propertyId:30,unitId:179,packageSha256:sha,sourceSha256:sha,packageSizeBytes:bytes.length,sourceSizeBytes:bytes.length,portalImportCandidate:true,reviewState:'reviewed_signed_lease_import_candidate'};
 return {root,snapshot,row,file,t,person};}
test('plan resolves source crosswalk and verifies bytes without account or upload writes',async()=>{const f=await fixture();try{const result=await provisionImportedTenants({manifest:{eligibleFiles:[f.file],heldAccounts:[]},roster:[f.row],packageRoot:f.root,actor:'',apply:false},{snapshot:async()=>f.snapshot,accounts:async()=>[],createPending:async()=>{throw Error('write')},upload:async()=>{throw Error('write')},verifyDocument:async()=>{throw Error('write')}});assert.equal(result.accountsToCreate,1);assert.equal(result.leaseFiles,1);assert.equal(result.activationTokensCreated,0);}finally{await rm(f.root,{recursive:true,force:true});}});
test('activated account is preserved and missing email holds account only, not reviewed lease',async()=>{const f=await fixture();try{const deps:any={snapshot:async()=>f.snapshot,accounts:async()=>[{id:'existing',email:f.person.email,personId:f.person.id,tenancyId:f.t.id,status:'active'}],createPending:async()=>{throw Error('must preserve')},upload:async()=>({id:'doc'}),verifyDocument:async()=>{}};const input={manifest:{eligibleFiles:[f.file],heldAccounts:[]},roster:[f.row],packageRoot:f.root,actor:'manager',apply:true};assert.equal((await provisionImportedTenants(input,deps)).accountsPreserved,1);f.row.primaryEmail=null;assert.equal((await provisionImportedTenants(input,{...deps,accounts:async()=>[]})).missingEmailHolds,1);}finally{await rm(f.root,{recursive:true,force:true});}});
test('wrong primary contact, held lease, and tampered bytes reject before writes',async()=>{const f=await fixture();try{const deps:any={snapshot:async()=>f.snapshot,accounts:async()=>[],createPending:async()=>{throw Error('write')},upload:async()=>{throw Error('write')}};const input={manifest:{eligibleFiles:[f.file],heldAccounts:[]},roster:[f.row],packageRoot:f.root,actor:'manager',apply:true};await assert.rejects(provisionImportedTenants({...input,roster:[{...f.row,primaryContactId:999}]},deps));await assert.rejects(provisionImportedTenants({...input,manifest:{...input.manifest,heldAccounts:[{sourceTenantId:873}]}},deps));await writeFile(join(f.root,'files/test.pdf'),'%PDF-tampered');await assert.rejects(verifiedLeaseBytes(f.root,f.file));}finally{await rm(f.root,{recursive:true,force:true});}});
test('retry reopens an exact existing lease instead of uploading or touching an activated account',async()=>{const f=await fixture();try{f.snapshot.documents.push({id:'existing-lease',tenancyId:f.t.id,personId:f.person.id,propertyId:f.t.propertyId,unitId:f.t.unitId,type:'lease',typeKnowledge:'manual',state:'verified',availability:'verified',storageKey:'private/existing',storageKeyKnowledge:'source',verifiedAt:'2026-09-07T00:00:00Z',checksumSha256:f.file.packageSha256,sizeBytes:f.file.packageSizeBytes,fileName:'test.pdf',mimeType:'application/pdf'});let verified=0;const result=await provisionImportedTenants({manifest:{eligibleFiles:[f.file],heldAccounts:[]},roster:[f.row],packageRoot:f.root,actor:'manager',apply:true},{snapshot:async()=>f.snapshot,accounts:async()=>[{id:'existing',email:f.person.email!,personId:f.person.id,tenancyId:f.t.id,status:'active'} as any],createPending:async()=>{throw Error('unexpected account mutation')},upload:async()=>{throw Error('unexpected duplicate upload')},verifyDocument:async()=>{verified++;}});assert.equal(result.leaseFilesAlreadyBound,1);assert.equal(verified,1);}finally{await rm(f.root,{recursive:true,force:true});}});
test('private package extraction rejects links before extraction and enforces byte limits',async()=>{
 const {extractPrivateLeasePackage}=await import('./provision-imported-tenants');const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const {symlink}=await import('node:fs/promises');const run=promisify(execFile);const f=await fixture();let extracted:string|undefined;
 try{const archive=join(f.root,'regular.tar.gz');await run('tar',['-czf',archive,'-C',f.root,'files/test.pdf']);extracted=await extractPrivateLeasePackage(archive);assert.ok((await verifiedLeaseBytes(extracted,f.file)).length>0);
 await symlink('/tmp/never-provision-this-file',join(f.root,'files/link.pdf'));const links=join(f.root,'links.tar.gz');await run('tar',['-czf',links,'-C',f.root,'files/link.pdf']);await assert.rejects(extractPrivateLeasePackage(links));
 await assert.rejects(verifiedLeaseBytes(f.root,{...f.file,packageSizeBytes:51*1024*1024,sourceSizeBytes:51*1024*1024}));
 }finally{if(extracted)await rm(extracted,{recursive:true,force:true});await rm(f.root,{recursive:true,force:true});}
});
test('future without an exact source tenancy is held without aborting other accounts',async()=>{const f=await fixture();try{const result=await provisionImportedTenants({manifest:{eligibleFiles:[],heldAccounts:[]},roster:[{...f.row,status:'future',leases:[],dateActiveLeaseIds:[]}],packageRoot:f.root,actor:'',apply:false},{snapshot:async()=>f.snapshot,accounts:async()=>[],createPending:async()=>{throw Error('write')},upload:async()=>{throw Error('write')},verifyDocument:async()=>{}});assert.equal(result.unresolvedTenancyHolds,1);assert.equal(result.accountsToCreate,0);}finally{await rm(f.root,{recursive:true,force:true});}});
test('another system property IDs and metadata-only lease rows never establish an existing verified source binding',async()=>{const f=await fixture();try{const deps:any={snapshot:async()=>f.snapshot,accounts:async()=>[],createPending:async()=>{},upload:async()=>{throw Error('write')},verifyDocument:async()=>{throw Error('metadata row must not be verified')}};const input={manifest:{eligibleFiles:[f.file],heldAccounts:[]},roster:[f.row],packageRoot:f.root,actor:'',apply:false};f.snapshot.documents.push({id:'metadata',type:'lease',state:'requested',tenancyId:f.t.id,personId:f.person.id,propertyId:f.t.propertyId,unitId:f.t.unitId,checksumSha256:f.file.packageSha256,sizeBytes:f.file.packageSizeBytes,fileName:'test.pdf',mimeType:'application/pdf'});assert.equal((await provisionImportedTenants(input,deps)).leaseFilesAlreadyBound,0);f.snapshot.properties.find(p=>p.id===f.t.propertyId)!.source!.system='other';await assert.rejects(provisionImportedTenants(input,deps),/source mismatch/);}finally{await rm(f.root,{recursive:true,force:true});}});
