import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getReportingDefinitions, type ReportDefinition } from "../../shared/reporting";
import { MIRROR_UNSUPPORTED } from "./ports/mirror-financial";
import type { CombinedFinancialReportId } from "./combined-financial-engine";

/**
 * The deployment conditions under which each engine reports "available".
 * The live catalog evaluates these per company; this inventory documents
 * them. No report is "not implemented".
 */
export function reportRuntimeCondition(definition: ReportDefinition): string {
  switch (definition.engineKey) {
    case "rental.operational":
    case "rental.operational-expanded":
    case "rental.leasing-agent":
    case "combined.projects":
    case "combined.investors":
    case "company.tasks":
    case "company.work-orders":
      return "Available";
    case "combined.property-statement":
      return "Available; measures without a source (collections, PM settlements, QuickBooks) are shown as unknown";
    case "combined.lender-package":
      return "Available; sections are ready only when matching saved runs exist";
    case "quickbooks.native-reports":
      return "Missing data until QuickBooks is configured and the entity has an active connection";
    case "company.time":
      return "Missing data until QuickBooks Time is connected";
    case "combined.owner-statements":
      return "Missing data until PM settlements are recorded";
    case "combined.forecast":
      return "Missing data: No approved forecast scenario (forecasting service port)";
    case "combined.financial": {
      const unsupported = MIRROR_UNSUPPORTED[definition.id as CombinedFinancialReportId];
      if (unsupported) return `Missing data: ${unsupported.reason}`;
      if (definition.setup.consolidation) return "Missing data until an approved account mapping and elimination version exist; otherwise available from the QuickBooks mirror (partial coverage)";
      return "Available from the QuickBooks mirror with partial coverage once an entity has an active connection";
    }
    default:
      return "Not implemented";
  }
}

function scopeText(definition: ReportDefinition): string {
  const parts = [definition.setup.entityScope === "exactly_one" ? "one entity" : definition.setup.entityScope === "one_or_more" ? "entities (required)" : "entities (optional)"];
  if (definition.setup.propertyScope) parts.push("properties");
  if (definition.setup.consolidation) parts.push("consolidation policy");
  if (definition.setup.forecastScenario) parts.push("forecast scenario");
  return parts.join(", ");
}

const cell = (value: string): string => value.replaceAll("|", "\\|");

export function renderReportingInventory(definitions: readonly ReportDefinition[] = getReportingDefinitions()): string {
  const header = "| ID | Title | Engine | Sources | Scope | Period | Basis | Filters | Runtime status |\n|---|---|---|---|---|---|---|---|---|";
  const rows = definitions.map(definition => `| \`${definition.id}\` | ${cell(definition.title)} | \`${definition.engineKey}\` | ${cell(definition.requiredSources.join(", "))} | ${scopeText(definition)} | ${definition.period.replace("_", "-")} | ${definition.basis.join("/")} | ${cell(definition.filters.map(filter => filter.name).join(", ") || "—")} | ${cell(reportRuntimeCondition(definition))} |`);
  return [header, ...rows].join("\n");
}

export const INVENTORY_START = "<!-- report-inventory:start (generated by `npx tsx server/reporting/inventory.ts --write`) -->";
export const INVENTORY_END = "<!-- report-inventory:end -->";
export const REPORTING_CONTRACT_PATH = fileURLToPath(new URL("../../docs/company/reporting-contract.md", import.meta.url));

export function withInventory(document: string, table = renderReportingInventory()): string {
  const start = document.indexOf(INVENTORY_START);
  const end = document.indexOf(INVENTORY_END);
  if (start < 0 || end < start) throw new Error("reporting-contract.md is missing the report inventory markers");
  return `${document.slice(0, start + INVENTORY_START.length)}\n${table}\n${document.slice(end)}`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1] && process.argv.includes("--write")) {
  writeFileSync(REPORTING_CONTRACT_PATH, withInventory(readFileSync(REPORTING_CONTRACT_PATH, "utf8")));
}
